import "server-only";
import type { DataSnapshot,Database } from "firebase-admin/database";
import { firebaseAdminDatabase } from "@/lib/firebase/admin";
import { mapAssignmentToReport } from "@/features/report/aor-report-contract";
import type { RawAssignmentRecord } from "@/features/assignment/assignment-types";
import type { AorReportRecord,ReportFilters } from "@/features/report/aor-report-types";
import type { AorReportRepository,ReportAuthorization } from "./report-repository";
const WINDOW=200,SCOPED=100,text=(value:unknown)=>String(value??"").trim(),lower=(value:unknown)=>text(value).toLowerCase();
const entries=(snapshot:DataSnapshot)=>{const rows:{key:string;value:RawAssignmentRecord}[]=[];snapshot.forEach(child=>{rows.push({key:child.key??"",value:child.val()??{}});});return rows;};
const isCandidate=(record:RawAssignmentRecord)=>Boolean(text(record.report_name)||text(record.report_url)||text(record.closed_date)||text(record.closed_datetime));
const duplicates=(rows:AorReportRecord[])=>{const seen=new Map<string,string[]>();rows.forEach(row=>{if(row.downloadUrl){const safe=`${row.storageBucket}/${row.storageObjectPath}`;seen.set(safe,[...(seen.get(safe)??[]),row.reportId]);}});return [...seen.values()].filter(ids=>ids.length>1).flat();};
function matches(row:AorReportRecord,filter:ReportFilters){const q=lower(filter.q);if(q&&!lower([row.towerId,row.assignmentId,row.riggerName,row.coordinatorName,row.company,row.fileName].join(" ")).includes(q))return false;for(const [wanted,value] of [[filter.tower,row.towerId],[filter.assignment,row.assignmentId],[filter.region,row.region],[filter.subRegion,row.subRegion],[filter.company,row.company],[filter.category,row.assignmentCategory],[filter.coordinator,row.coordinatorName],[filter.rigger,row.riggerName]])if(wanted&&!lower(value).includes(lower(wanted)))return false;if(filter.quality&&row.qualityStatus!==filter.quality)return false;if(filter.hasReport==="yes"&&row.qualityStatus!=="valid")return false;if(filter.hasReport==="no"&&row.qualityStatus==="valid")return false;if(filter.from&&row.closedDate?.match(/^\d{4}-/)&&row.closedDate<filter.from)return false;if(filter.to&&row.closedDate?.match(/^\d{4}-/)&&row.closedDate>filter.to)return false;return true;}
export class FirebaseAorReportRepository implements AorReportRepository {
  constructor(private readonly database:Database=firebaseAdminDatabase){}
  private assert(context:ReportAuthorization){if(!context.authorized)throw new Error("REPORT_ACCESS_DENIED");}
  private map(snapshot:DataSnapshot){return entries(snapshot).filter(({value})=>isCandidate(value)).map(({key,value})=>mapAssignmentToReport(key,value));}
  async getReportsList(filters:ReportFilters,context:ReportAuthorization){this.assert(context);const raw=entries(await this.database.ref("assignment").orderByKey().limitToLast(WINDOW+1).once("value"));const normalized=raw.slice(-WINDOW).filter(({value})=>isCandidate(value)).map(({key,value})=>mapAssignmentToReport(key,value));const duplicateIds=duplicates(normalized);duplicateIds.forEach(id=>{const row=normalized.find(item=>item.reportId===id);if(row&&!row.warnings.includes("duplicate-report-reference"))row.warnings.push("duplicate-report-reference");});const filtered=normalized.filter(row=>matches(row,filters)).sort((a,b)=>text(b.closedDateTime??b.closedDate).localeCompare(text(a.closedDateTime??a.closedDate))||b.sourceRecordKey.localeCompare(a.sourceRecordKey));const start=(filters.page-1)*filters.pageSize;return {rows:filtered.slice(start,start+filters.pageSize),filteredCount:filtered.length,scanned:Math.min(raw.length,WINDOW),bounded:true as const,hasNext:start+filters.pageSize<filtered.length,duplicateIds};}
  async getReportById(id:string,context:ReportAuthorization){const page=await this.getReportsList({q:"",tower:"",assignment:"",region:"",subRegion:"",company:"",category:"",coordinator:"",rigger:"",quality:"",hasReport:"",from:"",to:"",page:1,pageSize:100},context);if(page.rows.find(row=>row.reportId===id))return page.rows.find(row=>row.reportId===id)??null;const snapshot=await this.database.ref("assignment").orderByKey().limitToLast(WINDOW).once("value");return this.map(snapshot).find(row=>row.reportId===id)??null;}
  async getReportsForAssignment(id:string,context:ReportAuthorization){this.assert(context);return this.map(await this.database.ref("assignment").orderByChild("assignment_id").equalTo(id).limitToFirst(SCOPED).once("value"));}
  async getReportsForTower(id:string,context:ReportAuthorization){this.assert(context);return this.map(await this.database.ref("assignment").orderByChild("tower_id").equalTo(id).limitToLast(SCOPED).once("value"));}
}
