import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { PageHeader } from "@/components/application-shell/page-header";
import { AssignmentStatusBadge } from "@/components/assignment/assignment-status-badge";
import { isTerminalAssignment } from "@/features/assignment/assignment-command-contract";
import type { AssignmentListItem } from "@/features/assignment/assignment-types";
import type { RiggerDetailData } from "@/features/rigger/rigger-types";
import { RiggerContactActions } from "./rigger-contact-actions";
const display=(value:string|null)=>value||"Not available";
const Field=({label,value}:{label:string;value:string|null})=><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm">{display(value)}</dd></div>;
const Section=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">{title}</h2>{children}</section>;
export function RiggerDetail({data}:{data:RiggerDetailData}){
 const {rigger,assignments}=data,active=assignments.filter(row=>!isTerminalAssignment({assignment_state:row.assignment_state})),terminal=assignments.filter(row=>isTerminalAssignment({assignment_state:row.assignment_state})),latest=assignments[0]??null,completed=terminal.find(row=>row.closed_datetime||row.closed_date)??null;
 const organization=[rigger.company,rigger.department,rigger.region,rigger.subRegion,rigger.officeLocation].some(Boolean);
 const missing=[!rigger.name?"name":null,!rigger.email?"email":null].filter(Boolean).join(", ");
 return <div className="space-y-4"><PageHeader title={display(rigger.name)} description={`${display(rigger.position)} · ${display(rigger.status)}`} actions={<RiggerContactActions email={rigger.email} phone={rigger.phone}/>}/><Link href="/home/riggers" className="inline-flex min-h-11 items-center gap-2 font-semibold text-indigo-700 focus-visible:ring-2"><ArrowLeft className="size-4"/>Back to Riggers</Link>
 <Section title="Profile Information"><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Name" value={rigger.name}/><Field label="Email" value={rigger.email}/><Field label="Phone" value={rigger.phone}/><Field label="Role" value={rigger.role}/><Field label="Position" value={rigger.position}/><Field label="Status" value={rigger.status}/></dl></Section>
 <Section title="Organization">{organization?<dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Company" value={rigger.company}/><Field label="Department" value={rigger.department}/><Field label="Region" value={rigger.region}/><Field label="Sub Region" value={rigger.subRegion}/><Field label="Office Location" value={rigger.officeLocation}/><Field label="Type" value={rigger.type}/></dl>:<p className="mt-3 text-sm text-slate-600">Organization information is not available for this record.</p>}</Section>
 <Section title="Current Workload">{data.assignmentsFailed?<Failure/>:!rigger.name||!rigger.email?<p className="mt-3 text-sm text-amber-800">Assignment identity is unavailable, so workload cannot be resolved.</p>:active.length?<><p className="mt-2 text-sm text-slate-600">{active.length} active Assignments shown in the bounded recent result.</p><AssignmentCards rows={active}/></>:<p className="mt-3 text-sm text-slate-600">No active Assignments appear in the bounded recent result.</p>}</Section>
 <Section title="Recent Assignment History">{data.assignmentsFailed?<Failure/>:assignments.length?<><p className="mt-2 text-sm text-slate-600">Showing {assignments.length} recent Assignments matched by normalized email within the bounded indexed-name candidate query.</p>{data.assignmentWindowBounded?<p className="mt-2 rounded-lg bg-amber-50 p-2 text-sm text-amber-900">The 20-record recent-history limit was reached; this is not a lifetime total.</p>:null}<AssignmentTable rows={assignments}/><div className="lg:hidden"><AssignmentCards rows={assignments}/></div></>:<p className="mt-3 text-sm text-slate-600">No recent Assignment history was found for this Rigger identity.</p>}</Section>
 <Section title="Activity Information"><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Last Assignment date" value={latest?.created_datetime??latest?.created_date??null}/><Field label="Most recent completed Assignment" value={completed?.assignment_id??null}/><Field label="Completed date" value={completed?.closed_datetime??completed?.closed_date??null}/><Field label="Profile created date" value={rigger.createDateTime??rigger.createDate}/><Field label="Join date" value={rigger.joinDate}/></dl><p className="mt-3 text-xs text-slate-500">These timestamps describe stored account and Assignment records, not attendance or physical activity.</p></Section>
 <Section title="Record Compatibility Information"><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Primary Assignment identity" value={rigger.email?"Normalized rigger_email":"Not available"}/><Field label="Candidate query" value={rigger.name?"Exact Rigger name/date composite":"Not available"}/><Field label="Missing required identity fields" value={missing||"None"}/><Field label="Historical fallback identifiers" value="None used"/></dl></Section>
 </div>
}
function Failure(){return <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">Assignment information could not be loaded. The Rigger profile remains available and no data was changed.</p>}
function AssignmentCards({rows}:{rows:AssignmentListItem[]}){return <div className="mt-4 grid gap-3"><>{rows.map(row=><article key={row.key} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="break-all font-semibold">{display(row.assignment_id)}</h3><AssignmentStatusBadge status={row.assignment_status}/></div><dl className="mt-3 grid grid-cols-2 gap-3"><Field label="Tower ID" value={row.tower_id}/><Field label="Category" value={row.assignment_category}/><Field label="State" value={row.assignment_state}/><Field label="Assignment time" value={row.created_datetime??row.created_date}/></dl><Actions row={row}/></article>)}</></div>}
function AssignmentTable({rows}:{rows:AssignmentListItem[]}){return <div className="mt-4 hidden overflow-hidden rounded-xl border lg:block"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-600"><tr>{["Assignment ID","Tower ID","Category","Status","State","Assignment Time","Finished Time","Actions"].map(h=><th key={h} scope="col" className="border-b px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.key}><td className="max-w-52 break-all px-3 py-3 font-semibold">{display(row.assignment_id)}</td><td className="px-3 py-3">{display(row.tower_id)}</td><td className="px-3 py-3">{display(row.assignment_category)}</td><td className="px-3 py-3"><AssignmentStatusBadge status={row.assignment_status}/></td><td className="px-3 py-3">{display(row.assignment_state)}</td><td className="px-3 py-3">{display(row.created_datetime??row.created_date)}</td><td className="px-3 py-3">{display(row.closed_datetime??row.closed_date)}</td><td className="px-3 py-3"><Actions row={row}/></td></tr>)}</tbody></table></div></div>}
function Actions({row}:{row:AssignmentListItem}){return <div className="mt-3 flex flex-wrap gap-3 text-sm lg:mt-0"><Link href={`/home/assignment/${encodeURIComponent(row.key)}`} aria-label={`View Assignment ${display(row.assignment_id)}`} className="inline-flex min-h-11 items-center font-semibold text-indigo-700 focus-visible:ring-2">View Assignment</Link>{row.tower_id?<Link href={`/home/towers?q=${encodeURIComponent(row.tower_id)}`} aria-label={`Search Tower ${row.tower_id}`} className="inline-flex min-h-11 items-center font-semibold text-indigo-700 focus-visible:ring-2">Search Tower</Link>:null}</div>}
