"use client";
import Link from "next/link";
import { usePathname,useRouter,useSearchParams } from "next/navigation";
import { useState,useTransition } from "react";
import { Eye,RefreshCw,Search,X } from "lucide-react";
import { PageHeader } from "@/components/application-shell/page-header";
import type { RiggerListQuery } from "@/features/rigger/rigger-query-contract";
import type { RiggerListItem,RiggerListResult } from "@/features/rigger/rigger-types";
const display=(value:string|null)=>value||"Not available";
const inputClass="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500";
export function RiggerDirectory({result,query}:{result:RiggerListResult;query:RiggerListQuery}){
 const router=useRouter(),pathname=usePathname(),params=useSearchParams(),[pending,startTransition]=useTransition();
 const [draft,setDraft]=useState({q:query.q,status:query.status,company:query.company});
 const navigate=(changes:Record<string,string|null>,reset=true)=>{const next=new URLSearchParams(params.toString());for(const[k,v]of Object.entries(changes)){if(v)next.set(k,v);else next.delete(k);}if(reset)next.delete("cursor");startTransition(()=>router.push(`${pathname}?${next}`))};
 const clear=()=>{setDraft({q:"",status:"",company:""});navigate({q:null,status:null,company:null})};
 const activeRiggers=result.rows.filter(row=>String(row.status).toLowerCase()==="active").length,withWork=result.rows.filter(row=>row.workload.activeAssignments>0).length,activeAssignments=result.rows.reduce((sum,row)=>sum+row.workload.activeAssignments,0);
 return <div className={`space-y-4 ${pending?"opacity-70":""}`} aria-busy={pending}><PageHeader title="Riggers" description="Browse registered riggers and inspect their current Assignment workload." actions={<button type="button" onClick={()=>startTransition(()=>router.refresh())} disabled={pending} className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-semibold focus-visible:ring-2"><RefreshCw className={`size-4 ${pending?"animate-spin":""}`} aria-hidden="true"/>Refresh</button>}/>
 <section aria-labelledby="rigger-filters" className="rounded-2xl border bg-white p-4 shadow-sm"><h2 id="rigger-filters" className="text-sm font-semibold">Search and filters</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-medium">Keyword<input value={draft.q} onChange={e=>setDraft({...draft,q:e.target.value})} onKeyDown={e=>{if(e.key==="Enter")navigate(draft)}} placeholder="Name, email, phone, or company" className={inputClass}/></label><label className="text-sm font-medium">Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})} className={inputClass}><option value="">All statuses</option><option>Active</option><option>Not Active</option></select></label><label className="text-sm font-medium">Company<input value={draft.company} onChange={e=>setDraft({...draft,company:e.target.value})} className={inputClass}/></label></div><div className="mt-4 flex gap-2"><button type="button" onClick={()=>navigate(draft)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-indigo-700 px-4 text-sm font-semibold text-white focus-visible:ring-2"><Search className="size-4"/>Apply Filters</button><button type="button" onClick={clear} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 text-sm font-semibold focus-visible:ring-2"><X className="size-4"/>Clear Filters</button></div></section>
 <p className="sr-only" aria-live="polite">{result.rows.length} Riggers loaded.</p>
 <section aria-label="Bounded Rigger summary" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Riggers in current result",result.rows.length],["Active Riggers shown",activeRiggers],["Riggers with active Assignments",withWork],["Active Assignments in current result",activeAssignments]].map(([label,value])=><article key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-medium uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="text-xs text-slate-500">Bounded result</p></article>)}</section>
 {result.workloadWindowBounded?<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Workload values use the newest bounded 1,000-Assignment key window and may be incomplete.</p>:null}
 {result.rows.length?<Results rows={result.rows}/>:<section className="rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="font-semibold">{query.q||query.status||query.company?"No matching Riggers":"No registered Riggers"}</h2><p className="mt-2 text-sm text-slate-600">No Riggers were found in this bounded read.</p></section>}
 <nav aria-label="Rigger pagination" className="flex flex-col gap-3 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-600">Showing {result.rows.length} Riggers · scanned at most {result.scanned} users</p><div className="flex flex-wrap items-center gap-2"><label className="text-sm">Rows per page<select value={query.pageSize} onChange={e=>navigate({pageSize:e.target.value})} className="ml-2 min-h-11 rounded-lg border px-2"><option>25</option><option>50</option><option>100</option></select></label><Link aria-disabled={!query.cursor} href="/home/riggers" className={`inline-flex min-h-11 items-center rounded-xl border px-3 text-sm font-semibold ${!query.cursor?"pointer-events-none opacity-40":""}`}>First page</Link><button type="button" disabled={!result.nextCursor||pending} onClick={()=>navigate({cursor:result.nextCursor},false)} className="min-h-11 rounded-xl border px-3 text-sm font-semibold disabled:opacity-40 focus-visible:ring-2">Next</button></div></nav></div>
}
function Results({rows}:{rows:RiggerListItem[]}){return <section aria-label="Rigger results"><div className="hidden overflow-hidden rounded-2xl border bg-white shadow-sm lg:block"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-600"><tr>{["Rigger","Email","Status","Company","Region","Active Assignments","Recent Assignment","Last Activity","Action"].map(h=><th key={h} scope="col" className="border-b px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.firebaseKey}><td className="max-w-52 break-words px-3 py-3 font-semibold">{display(row.name)}</td><td className="max-w-64 break-all px-3 py-3">{display(row.email)}</td><td className="px-3 py-3"><Status value={row.status}/></td><td className="px-3 py-3">{display(row.company)}</td><td className="px-3 py-3">{display(row.region)}</td><td className="px-3 py-3">{row.workload.activeAssignments}</td><td className="max-w-52 break-words px-3 py-3">{display(row.workload.latestAssignment?.assignment_id??null)}</td><td className="px-3 py-3">{display(row.workload.latestAssignment?.created_datetime??row.workload.latestAssignment?.created_date??null)}</td><td className="px-3 py-3"><View row={row}/></td></tr>)}</tbody></table></div></div><div className="grid gap-3 lg:hidden">{rows.map(row=><article key={row.firebaseKey} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><h3 className="break-words font-semibold">{display(row.name)}</h3><Status value={row.status}/></div><p className="mt-1 break-all text-sm text-slate-600">{display(row.email)}</p><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><Field label="Company" value={display(row.company)}/><Field label="Region" value={display(row.region)}/><Field label="Active Assignments" value={String(row.workload.activeAssignments)}/><Field label="Latest Assignment" value={display(row.workload.latestAssignment?.assignment_id??null)}/><Field label="Latest Assignment date" value={display(row.workload.latestAssignment?.created_datetime??row.workload.latestAssignment?.created_date??null)}/></dl><div className="mt-3"><View row={row}/></div></article>)}</div></section>}
function Status({value}:{value:string|null}){return <span className="inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold ring-1 ring-slate-200">Status: {display(value)}</span>}
function Field({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-medium uppercase text-slate-500">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>}
function View({row}:{row:RiggerListItem}){return <Link href={`/home/riggers/${encodeURIComponent(row.firebaseKey)}`} aria-label={`View details for Rigger ${display(row.name)}`} className="inline-flex min-h-11 items-center gap-2 font-semibold text-indigo-700 focus-visible:ring-2"><Eye className="size-4"/>View Details</Link>}

