/* eslint-disable @typescript-eslint/no-explicit-any */
import"server-only";import packageJson from"../../../package.json";import{firebaseAdminApp,firebaseAdminAuth,firebaseAdminDatabase,firebaseAdminStorage}from"@/lib/firebase/admin";import{FirebaseAuditCenterRepository}from"@/server/audit/firebase-audit-center-repository";import{snapshot as operationalSnapshot}from"@/server/operations/health-route";import{assignmentWorkload,userWorkload,systemFailureEvents,aggregateHealthStatus,type HealthCheckResult,type HealthStatus,type SystemHealthSnapshot}from"@/features/system-health/system-health";
const TIMEOUT=4000,WINDOW=500;type Row=Record<string,unknown>;const entries=(snapshot:any)=>{const rows:Row[]=[];snapshot.forEach((child:any)=>rows.push({__key:child.key??"",...(child.val()??{})}));return rows};
class HealthTimeout extends Error{}async function timed<T>(work:Promise<T>){return Promise.race([work,new Promise<T>((_,reject)=>setTimeout(()=>reject(new HealthTimeout()),TIMEOUT))])}
async function check(id:string,label:string,code:string,work:()=>Promise<{message:string;metadata?:Record<string,string|number|boolean|null>;status?:HealthStatus}>,scope:string,limitation:string,nextAction:string):Promise<HealthCheckResult>{const start=performance.now(),checkedAt=new Date().toISOString();try{const result=await timed(work());return{id,label,status:result.status??"healthy",checkedAt,durationMs:Math.round(performance.now()-start),message:result.message,errorCode:null,metadata:result.metadata??{},checkType:"live read-only check",scope,limitation,nextAction}}catch(error){return{id,label,status:error instanceof HealthTimeout?"degraded":"unavailable",checkedAt,durationMs:Math.round(performance.now()-start),message:error instanceof HealthTimeout?"The check exceeded the 4-second timeout.":"The service could not be checked.",errorCode:error instanceof HealthTimeout?"api_timeout":code,metadata:{},checkType:"live read-only check",scope,limitation,nextAction}}}
async function readWindow(path:string){return entries(await firebaseAdminDatabase.ref(path).orderByKey().limitToLast(WINDOW+1).once("value")).slice(-WINDOW)}
export class SystemHealthService{async run():Promise<SystemHealthSnapshot>{const checksPromise=Promise.all([
 check("auth","Firebase Authentication","auth_unavailable",async()=>{if(!firebaseAdminApp.name)throw new Error();await firebaseAdminAuth.listUsers(1);return{message:"Admin SDK initialized and a bounded identity read succeeded.",metadata:{maximumResults:1}}},"Firebase Authentication metadata","Requires permission to list one identity; no user details are returned.","Verify Admin SDK credentials and Auth service availability."),
 check("database","Realtime Database","database_unavailable",async()=>{await firebaseAdminDatabase.ref("user").orderByKey().limitToFirst(1).once("value");return{message:"A bounded read from a known operational path succeeded.",metadata:{maximumRecords:1}}},"Known `user` path, at most one record","Success does not validate every RTDB path or index.","Review Firebase status and server credentials."),
 check("storage","Firebase Storage","storage_unavailable",async()=>{await firebaseAdminStorage.bucket().getMetadata();return{message:"Bucket metadata is reachable."}},"Configured default bucket metadata","No object is downloaded, uploaded, or deleted.","Verify bucket configuration and Storage IAM."),
 check("web","Web Application","api_unhealthy",async()=>{const value=operationalSnapshot();return{status:value.health.ready?"healthy":"degraded",message:value.health.ready?"Internal readiness checks passed.":"Internal readiness has blockers.",metadata:{live:value.health.live,ready:value.health.ready,blockerCount:value.health.blockers.length}}},"In-process readiness contract","This does not make an external HTTP round trip.","Open deployment readiness diagnostics."),
 check("mobile_api","Mobile API","api_unhealthy",async()=>{const value=operationalSnapshot();const ready=value.health.checks.compatibility_subsystem;return{status:ready?"healthy":"unavailable",message:ready?"All compatibility routes are registered.":"The compatibility route inventory is incomplete.",metadata:{compatibilityReady:ready}}},"Mobile compatibility policy registry","No authenticated client request or mutation is executed.","Review mobile API compatibility route registration."),
 check("notifications","Notifications","notification_repository_unavailable",async()=>{await firebaseAdminDatabase.ref("notification_user").orderByKey().limitToLast(1).once("value");return{message:"The notification root accepted a bounded metadata read.",metadata:{maximumUsers:1}}},"Notification ownership root, at most one user branch","Delivery failures are console-only and cannot be counted historically.","Review application logs for notification_delivery_failed."),
 check("reports","Reports","report_service_unavailable",async()=>{await firebaseAdminDatabase.ref("assignment").orderByKey().limitToLast(1).once("value");return{message:"Report source is readable; Storage health is reported separately.",metadata:{maximumAssignments:1}}},"Assignment-backed report source, at most one record","Does not generate or download a report.","Review report export audit failures and Storage health."),
 check("audit","Audit system","audit_source_partial",async()=>{const result=await new FirebaseAuditCenterRepository().list();return{status:result.unavailableSources.length?"degraded":"healthy",message:result.unavailableSources.length?"One or more bounded audit sources were unavailable.":"Bounded audit sources are readable.",metadata:{eventCount:result.events.length,unavailableSourceCount:result.unavailableSources.length,bounded:true}}},"Existing bounded Audit Center sources","Audit history is bounded and is not continuous monitoring.","Open Audit Center and inspect source warnings.")]);
 const [checksResult,assignmentsResult,usersResult,auditResult]=await Promise.allSettled([checksPromise,timed(readWindow("assignment")),timed(readWindow("user")),timed(new FirebaseAuditCenterRepository().list())]);const checks=checksResult.status==="fulfilled"?checksResult.value:[],assignments=assignmentsResult.status==="fulfilled"?assignmentWorkload(assignmentsResult.value):{scope:"Unavailable",bounded:true},users=usersResult.status==="fulfilled"?userWorkload(usersResult.value):{scope:"Unavailable",bounded:true},audit=auditResult.status==="fulfilled"?systemFailureEvents(auditResult.value.events):{issues:[],critical:0,scope:"Unavailable",bounded:true as const},recentEvents=auditResult.status==="fulfilled"?auditResult.value.events.slice(0,20).map(event=>({key:event.canonicalKey,module:event.module,action:event.actionLabel,timestamp:event.timestamp.iso,severity:event.severity,result:event.result||null,summary:event.reason||event.targetLabel||null})):[];const partial=checks.some(x=>x.status!=="healthy")||[assignmentsResult,usersResult,auditResult].some(x=>x.status==="rejected")||(auditResult.status==="fulfilled"&&auditResult.value.unavailableSources.length>0),overallStatus=aggregateHealthStatus(checks,audit.critical);const environment=process.env.NODE_ENV==="production"?"Production":process.env.NODE_ENV==="development"?"Development":"Test",build=process.env.VERCEL_GIT_COMMIT_SHA?.slice(0,12)||process.env.BUILD_ID?.slice(0,40)||"Not available";return{overallStatus,checkedAt:new Date().toISOString(),checks,workload:{assignments,users},failures:audit,recentEvents,warnings:[{code:"bounded_query_fallback",message:"Workload and audit counts cover bounded recent windows, not full-system totals."},{code:"missing_index_warning",message:"Notification unread checks use a bounded push-key fallback because deployed RTDB index rules are unavailable."}],environment:{name:environment,nodeVersion:process.version,nextVersion:String(packageJson.dependencies.next),firebaseAdminVersion:String(packageJson.dependencies["firebase-admin"]),applicationVersion:packageJson.version,buildId:build,uptimeSeconds:Math.floor(process.uptime()),serverTimezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Not available",runtimeMode:process.env.NODE_ENV??"unknown"},partial}}
}
