import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { classifyPasswordResetError, PASSWORD_RESET_PUBLIC_MESSAGE, requestPasswordReset } from "../../src/features/authentication/password-reset.mjs";
test("reset calls and awaits Firebase sendPasswordResetEmail with the correct Auth and trimmed email",async()=>{const auth={name:"correct-auth"},calls=[];let resolved=false;const pending=requestPasswordReset({auth,email:"  User@Example.com  ",send:async(...args)=>{calls.push(args);await Promise.resolve();resolved=true}});assert.equal(resolved,false);const result=await pending;assert.equal(resolved,true);assert.deepEqual(calls,[[auth,"User@Example.com"]]);assert.equal(result.message,PASSWORD_RESET_PUBLIC_MESSAGE);});
test("Firebase errors remain private while safe development classification is logged",async()=>{for(const [code,outcome] of [["auth/user-not-found","auth_user_not_found"],["auth/invalid-email","invalid_email"],["auth/network-request-failed","network_request_failed"],["auth/too-many-requests","too_many_requests"],["auth/unauthorized-domain","unauthorized_continue_uri"]]){const logs=[];const result=await requestPasswordReset({auth:{},email:"user@example.com",send:async()=>{throw {code}},log:event=>logs.push(event)});assert.equal(result.success,true);assert.equal(result.message,PASSWORD_RESET_PUBLIC_MESSAGE);assert.deepEqual(logs,[{outcome}]);assert.equal(classifyPasswordResetError({code}),outcome);}});
test("invalid email is handled without making a Firebase request",async()=>{let called=false;const logs=[];const result=await requestPasswordReset({auth:{},email:" invalid ",send:async()=>{called=true},log:event=>logs.push(event)});assert.equal(called,false);assert.equal(result.success,true);assert.deepEqual(logs,[{outcome:"invalid_email"}]);});
test("client wiring uses Firebase client Auth, supplies no custom ActionCodeSettings, and logs only hashes",async()=>{const source=await read("services/authentication/client-authentication.ts");assert.match(source,/sendPasswordResetEmail/);assert.match(source,/auth: firebaseAuth/);assert.match(source,/send: sendPasswordResetEmail/);assert.match(source,/projectIdHash: shortSafeHash/);assert.match(source,/authDomainHash: shortSafeHash/);assert.match(source,/apiKeyHash: shortSafeHash/);assert.match(source,/actionCodeSettings: "default_firebase_handler"/);assert.doesNotMatch(source,/continueUrl|handleCodeInApp/);});
test("dialog prevents double submission and preserves generic future-tense guidance",async()=>{const source=await read("components/authentication/reset-password-dialog.tsx");assert.match(source,/if \(isSubmitting \|\| !canSubmit\)/);assert.match(source,/disabled=\{isSubmitting \|\| !canSubmit\}/);assert.match(source,/PASSWORD_RESET_PUBLIC_MESSAGE/);assert.doesNotMatch(PASSWORD_RESET_PUBLIC_MESSAGE,/has been sent|have been sent/i);});
test("reset flow generates no password, touches no RTDB profile, and invite behavior remains unchanged",async()=>{const [client,feature,invite]=await Promise.all([read("services/authentication/client-authentication.ts"),read("features/authentication/password-reset.mjs"),read("server/admin/user-invitation-service.ts")]);const start=client.indexOf("export async function resetPassword"),end=client.indexOf("const passwordError",start),resetFunction=client.slice(start,end);assert.doesNotMatch(resetFunction+feature,/createUser|updatePassword|firebaseAdminDatabase/);assert.match(invite,/this\.auth\.create\(input\.email, temporaryPassword\(\), input\.name\)/);});
function read(path){return readFile(new URL(`../../src/${path}`,import.meta.url),"utf8")}