/* eslint-disable @typescript-eslint/no-explicit-any */
import"server-only";import{firebaseAdminDatabase}from"@/lib/firebase/admin";import{filterRows,REPORT_EXPORT_LIMIT,REPORT_PREVIEW_LIMIT,type ReportType}from"@/features/reports-center/reports-center";import{mapAssignmentToReport}from"@/features/report/aor-report-contract";import{normalizeAuditEvent}from"@/features/audit/audit-center";
const WINDOW=500,text=(v:unknown)=>v??null;type Row=Record<string,unknown>;const entries=(snapshot:any)=>{const out:{key:string;value:Row}[]=[];snapshot.forEach((child:any)=>out.push({key:child.key??"",value:child.val()??{}}));return out};

async function readRoot(path:string){return entries(await firebaseAdminDatabase.ref(path).orderByKey().limitToLast(WINDOW+1).once("value"))}
function base(key:string,value:Row,keyName:string){return{__key:key,[keyName]:key,...value}}
async function rowsFor(type:ReportType,sensitive:boolean):Promise<{rows:Row[];sources:string[];partial:boolean}>{
 if(type==="assignment")return{rows:(await readRoot("assignment")).slice(-WINDOW).map(x=>{const r=base(x.key,x.value,"assignment_key");if(!sensitive)delete r.report_url;return r}),sources:["assignment"],partial:false};
 if(type==="tower")return{rows:(await readRoot("tower")).slice(-WINDOW).map(x=>base(x.key,x.value,"tower_key")),sources:["tower"],partial:false};
 if(type==="cell")return{rows:(await readRoot("cell")).slice(-WINDOW).map(x=>base(x.key,x.value,"cell_key")),sources:["cell"],partial:false};
 if(type==="user"){const source=(await readRoot("user")).slice(-WINDOW);const rows=source.map(x=>({...base(x.key,x.value,"user_key"),identity_health:"not_checked",profile_updated_at:x.value.photo_updated_at??x.value.updated_at??null}));return{rows,sources:["user","firebase_auth"],partial:false}}
 if(type==="aor"){const source=(await readRoot("assignment")).slice(-WINDOW);return{rows:source.map(x=>{const r=mapAssignmentToReport(x.key,x.value as any);return{__key:x.key,report_record_key:r.reportId,assignment_key:x.key,assignment_id:r.assignmentId,tower_id:r.towerId,report_name:r.fileName,generated_date:r.closedDateTime??r.closedDate,rigger:r.riggerName,coordinator:r.coordinatorName,company:r.company,status:r.qualityStatus,download_available:r.qualityStatus==="valid"}}),sources:["assignment"],partial:false}}
 if(type==="audit"){const roots=await Promise.allSettled([readRoot("administrator_audit"),readRoot("assignment_audit"),readRoot("tower_audit")]);const rows:Row[]=[];roots.forEach((result,index)=>{if(result.status!=="fulfilled")return;const root=["administrator_audit","assignment_audit","tower_audit"][index];for(const x of result.value.slice(-WINDOW)){if(root==="administrator_audit"){const e=normalizeAuditEvent(root,"",x.key,x.value);rows.push({__key:e.canonicalKey,event_key:e.eventKey,module:e.module,action:e.action,timestamp:e.timestamp.iso,target:e.targetId||e.targetKey,actor:e.actorName||e.actorEmail||e.actorUid,reason:e.reason,severity:e.severity,changed_fields:e.changedFields,result:e.result,operation_id:(e.metadata as any)?.operation_id??(e.metadata as any)?.requestIdentifier??null})}else for(const [childKey,raw] of Object.entries(x.value)){const e=normalizeAuditEvent(root,x.key,childKey,raw);rows.push({__key:e.canonicalKey,event_key:e.eventKey,module:e.module,action:e.action,timestamp:e.timestamp.iso,target:e.targetId||e.targetKey,actor:e.actorName||e.actorEmail||e.actorUid,reason:e.reason,severity:e.severity,changed_fields:e.changedFields,result:e.result,operation_id:(e.metadata as any)?.operation_id??null})}}});return{rows,sources:["administrator_audit","assignment_audit","tower_audit"],partial:roots.some(x=>x.status==="rejected")}}
 const [users,assignments]=await Promise.all([readRoot("user"),readRoot("assignment")]);const riggers=users.slice(-WINDOW).filter(x=>String(x.value.role??"").toLowerCase()==="rigger");return{rows:riggers.map(x=>{const email=String(x.value.email??"").toLowerCase(),name=String(x.value.name??"").toLowerCase(),work=assignments.filter(a=>String(a.value.rigger_email??"").toLowerCase()===email||(!email&&String(a.value.rigger_name??"").toLowerCase()===name)),completed=work.filter(a=>String(a.value.completed??"").toLowerCase()==="true"||String(a.value.assignment_state??"").toLowerCase()==="completed").length,active=work.filter(a=>["active","accepted","working","in progress"].includes(String(a.value.assignment_state??"").toLowerCase())).length,paused=work.filter(a=>String(a.value.assignment_state??"").toLowerCase()==="paused").length,rejected=work.filter(a=>/reject|drop/.test(String(a.value.assignment_state??"").toLowerCase())).length;return{__key:x.key,rigger_key:x.key,name:x.value.name,email:sensitive?x.value.email:null,company:x.value.company,region:x.value.region,total_assigned:work.length,active,completed,paused,rejected_dropped:rejected,completion_rate:work.length?Number((completed/work.length*100).toFixed(2)):0}}),sources:["user","assignment"],partial:false}}
export async function generateReport(type:ReportType,filters:Record<string,string>,columns:string[],mode:"preview"|"export"){const source=await rowsFor(type,true),filtered=filterRows(source.rows,filters),limit=mode==="preview"?REPORT_PREVIEW_LIMIT:REPORT_EXPORT_LIMIT,exceeded=filtered.length>limit;return{rows:filtered.slice(0,limit).map(row=>Object.fromEntries(columns.map(key=>[key,text(row[key])]))),matchedInLoadedScope:filtered.length,scanned:source.rows.length,bounded:true,limit,exceeded,partial:source.partial,sources:source.sources}}
