"use client";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useState, useTransition } from "react";
import { Eye, MapPinned, RadioTower, RefreshCw, Search, X } from "lucide-react";
import { PageHeader } from "@/components/application-shell/page-header";
import { towerDisplay } from "@/features/tower/tower-mapper";
import type { TowerListQuery } from "@/features/tower/tower-query-contract";
import type { Tower } from "@/features/tower/tower-types";
import type { TowerListResult } from "@/server/tower/tower-repository";
import { TowerCreateDialog } from "./tower-create-dialog";
import { TowerEditDialog } from "./tower-edit-dialog";
import { TowerDependencyViewer } from "./tower-dependency-viewer";
import { TowerAuditTimeline } from "./tower-audit-timeline";
const filters = [
  ["region","Region"],["subRegion","Sub Region"],["province","Province"],["kabupaten","Kabupaten"],
  ["cluster","Cluster"],["siteType","Site Type"],["btsType","BTS Type"],
] as const;
const inputClass = "mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 outline-none focus-visible:ring-2 focus-visible:ring-indigo-500";
export function TowerDirectory({ result, query, canCreate=false, canEdit=false, canViewDependencies=false, initialCreate=false, initialLatitude="", initialLongitude="" }: { result: TowerListResult; query: TowerListQuery; canCreate?:boolean;canEdit?:boolean;canViewDependencies?:boolean;initialCreate?:boolean;initialLatitude?:string;initialLongitude?:string }) {
  const router=useRouter(), pathname=usePathname(), search=useSearchParams();
  const [pending,startTransition]=useTransition();
  const [draft,setDraft]=useState<Record<string,string>>({q:query.q,...Object.fromEntries(filters.map(([key])=>[key,query[key]]))});
  const navigate=(changes:Record<string,string|null>)=>{const next=new URLSearchParams(search.toString());Object.entries(changes).forEach(([k,v])=>v?next.set(k,v):next.delete(k));startTransition(()=>router.push(`${pathname}?${next}`));};
  const apply=()=>navigate({...draft,cursor:null});
  const clear=()=>{const empty=Object.fromEntries(["q",...filters.map(([key])=>key)].map(k=>[k,""]));setDraft(empty);navigate({...empty,cursor:null});};
  const unique=(field:keyof Tower)=>new Set(result.rows.map(row=>towerDisplay(row[field] as never)).filter(v=>v!=="—")).size;
  return <div className={`space-y-4 transition-opacity ${pending?"opacity-70":""}`} aria-busy={pending}>
    <PageHeader title="Towers" description="Manage telecom tower master data." actions={<div className="flex flex-wrap gap-2">{canCreate?<TowerCreateDialog initialOpen={initialCreate} latitude={initialLatitude} longitude={initialLongitude}/>:null}<Link href={`/home/towers/map?${new URLSearchParams([...search.entries()].filter(([key])=>!["cursor","page","create","latitude","longitude"].includes(key))).toString()}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-indigo-200 bg-indigo-50 px-4 text-sm font-semibold text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500"><MapPinned className="size-4" aria-hidden="true"/>Map View</Link><button type="button" disabled={pending} onClick={()=>startTransition(()=>router.refresh())} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-indigo-500"><RefreshCw className={`size-4 ${pending?"animate-spin motion-reduce:animate-none":""}`} aria-hidden="true"/>Refresh</button></div>} />
    {canCreate?<div className="flex justify-end"><Link href={`/home/towers/import-export?${new URLSearchParams([...search.entries()].filter(([key])=>!["cursor","page"].includes(key))).toString()}`} className="inline-flex min-h-11 items-center rounded-xl border border-indigo-200 bg-white px-4 text-sm font-semibold text-indigo-700">Import / Export</Link></div>:null}
    <section aria-labelledby="tower-search" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
      <h2 id="tower-search" className="text-sm font-semibold">Search and filters</h2>
      <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-sm font-medium text-slate-700 sm:col-span-2">Keyword<input value={draft.q} onChange={e=>setDraft({...draft,q:e.target.value})} onKeyDown={e=>{if(e.key==="Enter")apply();}} placeholder="Tower ID, site name, or cluster" className={inputClass}/></label>
        {filters.map(([key,label])=><label key={key} className="text-sm font-medium text-slate-700">{label}<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} className={inputClass}/></label>)}
      </div>
      <div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={apply} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-indigo-700 px-4 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-indigo-500"><Search className="size-4" aria-hidden="true"/>Apply Filters</button><button type="button" onClick={clear} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 px-4 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-indigo-500"><X className="size-4" aria-hidden="true"/>Clear Filters</button></div>
    </section>
    <p className="sr-only" aria-live="polite">{result.rows.length} Tower results loaded.</p>
    <section aria-label="Bounded result summary" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total results",result.rows.length],["Regions represented",unique("region")],["Sub-regions represented",unique("sub_region")],["Clusters represented",unique("new_cluster_name")]].map(([label,value])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">Current bounded result</p></article>)}</section>
    {result.rows.length?<TowerResults rows={result.rows} canEdit={canEdit} canViewDependencies={canViewDependencies}/>:<section aria-labelledby="no-towers" className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><RadioTower className="mx-auto size-10 text-indigo-600" aria-hidden="true"/><h2 id="no-towers" className="mt-3 font-semibold">{query.q||filters.some(([k])=>query[k])?"No matching Towers":"No Tower records"}</h2><p className="mt-2 text-sm text-slate-600">No records were found in this bounded read. Adjust or clear the criteria and try again.</p></section>}
    <nav aria-label="Tower pagination" className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-600">Showing {result.rows.length} results · scanned at most {result.scanned} records</p><div className="flex flex-wrap items-center gap-2"><label className="text-sm">Rows per page<select value={query.pageSize} onChange={e=>navigate({pageSize:e.target.value,cursor:null})} className="ml-2 min-h-11 rounded-lg border border-slate-300 px-2"><option>25</option><option>50</option><option>100</option></select></label><Link aria-disabled={!query.cursor} href={query.cursor?"/home/towers":"#"} className={`inline-flex min-h-11 items-center rounded-xl border px-3 text-sm font-semibold ${!query.cursor?"pointer-events-none opacity-40":""}`}>First page</Link><button type="button" disabled={!result.nextCursor||pending} onClick={()=>navigate({cursor:result.nextCursor})} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm font-semibold disabled:opacity-40 focus-visible:ring-2 focus-visible:ring-indigo-500">Next</button></div></nav>
  </div>;
}
function TowerResults({rows,canEdit,canViewDependencies}:{rows:Tower[];canEdit:boolean;canViewDependencies:boolean}) {
  return <section aria-label="Tower results"><div className="hidden overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm lg:block"><div className="max-h-[65vh] overflow-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr>{["Tower ID","Site ID","Site Name","Region","Sub Region","Province","Kabupaten","Cluster","Site Type","BTS Type","Coordinates","Action"].map(h=><th key={h} scope="col" className="border-b px-3 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.firebaseKey} className="hover:bg-indigo-50/50"><Cell value={row.tower_id} strong/><Cell value={row.site_id}/><Cell value={row.sitename}/><Cell value={row.region}/><Cell value={row.sub_region}/><Cell value={row.province}/><Cell value={row.kabupaten}/><Cell value={row.new_cluster_name}/><Cell value={row.site_type}/><Cell value={row.bts_type}/><td className="px-3 py-3 whitespace-nowrap">{towerDisplay(row.latitude)}, {towerDisplay(row.longitude)}</td><td className="px-3 py-3"><div className="flex items-center gap-3"><View tower={row}/>{canEdit?<TowerEditDialog tower={row} compact/>:null}{canViewDependencies?<TowerDependencyViewer tower={row} compact/>:null}<TowerAuditTimeline tower={row} compact/></div></td></tr>)}</tbody></table></div></div><div className="grid gap-4 lg:hidden">{rows.map(row=><article key={row.firebaseKey} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="break-words font-semibold">{towerDisplay(row.tower_id)}</h3><p className="mt-1 break-words text-xs text-slate-500">Site ID: {towerDisplay(row.site_id)}</p><p className="mt-1 break-words text-sm text-slate-600">{towerDisplay(row.sitename)}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Field label="Region / Sub Region" value={`${towerDisplay(row.region)} / ${towerDisplay(row.sub_region)}`}/><Field label="Kabupaten" value={towerDisplay(row.kabupaten)}/><Field label="Cluster" value={towerDisplay(row.new_cluster_name)}/><Field label="Site Type" value={towerDisplay(row.site_type)}/><Field label="BTS Type" value={towerDisplay(row.bts_type)}/></dl><div className="mt-4 flex flex-wrap items-center gap-3"><View tower={row} details/>{canEdit?<TowerEditDialog tower={row} compact/>:null}{canViewDependencies?<TowerDependencyViewer tower={row} compact/>:null}<TowerAuditTimeline tower={row} compact/></div></article>)}</div></section>;
}
function Cell({value,strong=false}:{value:unknown;strong?:boolean}){return <td className={`max-w-48 break-words px-3 py-3 ${strong?"font-semibold":""}`}>{towerDisplay(value as never)}</td>}
function Field({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>}
function View({tower,details=false}:{tower:Tower;details?:boolean}){return <Link href={`/home/towers/${encodeURIComponent(tower.firebaseKey)}`} aria-label={`View details for Tower ${towerDisplay(tower.tower_id)}`} className="inline-flex min-h-11 items-center gap-2 font-semibold text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500"><Eye className="size-4" aria-hidden="true"/>{details?"View Details":"View"}</Link>}
