"use client";

import Link from "next/link";
import { usePathname,useRouter,useSearchParams } from "next/navigation";
import { useMemo,useState,useTransition } from "react";
import { KeyRound,RefreshCw,Search,X } from "lucide-react";
import { PageHeader } from "@/components/application-shell/page-header";
import { administratorRoleContractState,administratorRoleDefinition,administratorRoleLabel,type AdministratorRoleContractState } from "@/features/admin/administrator-role-contract";
import type { AdminRoleSummary } from "@/features/admin/admin-types";
import { AdminEmptyState } from "./admin-page-state";

type ScopeFilter="all"|AdministratorRoleContractState;
const fieldClass="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500";
const scopeLabel:Record<AdministratorRoleContractState,string>={assignable:"Assignable",legacy:"Legacy read-only",privilege_only:"Privilege only",unsupported:"Unsupported",unknown:"Unknown"};
function description(role:AdminRoleSummary){const state=administratorRoleContractState(role.role);if(role.isAdministrator)return "Controls verified administrator access and is protected by final-administrator safeguards.";if(state==="legacy")return "Existing user role retained for compatibility; it cannot be newly assigned.";if(state==="privilege_only")return "Privilege field retained for compatibility; it cannot be assigned to users.";if(state==="unknown")return "Observed stored role outside the centralized assignable-role contract.";return "Current role with strict page privileges managed through the existing privilege matrix."}
function badgeClass(state:AdministratorRoleContractState){return state==="assignable"?"bg-emerald-50 text-emerald-800 ring-emerald-200":state==="legacy"?"bg-amber-50 text-amber-900 ring-amber-200":state==="privilege_only"?"bg-sky-50 text-sky-800 ring-sky-200":"bg-slate-100 text-slate-700 ring-slate-200"}

export function AdminRolesClient({roles}:{roles:AdminRoleSummary[]}){
 const router=useRouter(),pathname=usePathname(),params=useSearchParams(),[pending,startTransition]=useTransition();
 const appliedSearch=params.get("q")?.trim()??"",appliedScope=(params.get("scope")??"all") as ScopeFilter,appliedPrivileges=params.get("privileges")??"all";
 const [search,setSearch]=useState(appliedSearch),[scope,setScope]=useState<ScopeFilter>(["all","assignable","legacy","privilege_only","unsupported","unknown"].includes(appliedScope)?appliedScope:"all"),[privileges,setPrivileges]=useState(["all","yes","none"].includes(appliedPrivileges)?appliedPrivileges:"all");
 const filtered=useMemo(()=>roles.filter(role=>{const state=administratorRoleContractState(role.role),term=appliedSearch.toLowerCase();return(!term||[role.role,administratorRoleLabel(role.role),description(role)].some(value=>value.toLowerCase().includes(term)))&&(appliedScope==="all"||state===appliedScope)&&(appliedPrivileges==="all"||(appliedPrivileges==="yes"?role.enabledPageCount>0:role.enabledPageCount===0))}),[roles,appliedSearch,appliedScope,appliedPrivileges]);
 const apply=()=>{const next=new URLSearchParams();if(search.trim())next.set("q",search.trim());if(scope!=="all")next.set("scope",scope);if(privileges!=="all")next.set("privileges",privileges);startTransition(()=>router.push(`${pathname}${next.size?`?${next}`:""}`))};
 const clear=()=>{setSearch("");setScope("all");setPrivileges("all");startTransition(()=>router.push(pathname))};
 const withUsers=roles.filter(role=>role.userCount>0).length,protectedRoles=roles.filter(role=>role.isAdministrator).length,privilegeAssignments=roles.reduce((sum,role)=>sum+role.enabledPageCount,0);
 return <div className={`space-y-4 ${pending?"opacity-70":""}`} aria-busy={pending}>
  <PageHeader title="Roles" description="Manage access roles and review privilege coverage." actions={<button type="button" disabled={pending} onClick={()=>startTransition(()=>router.refresh())} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-800 shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 disabled:opacity-50"><RefreshCw aria-hidden="true" className={`size-4 ${pending?"animate-spin motion-reduce:animate-none":""}`}/>Refresh</button>}/>
  <section aria-label="Role summary" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total roles",roles.length,"Exact observed role inventory"],["Roles with users",withUsers,"Derived from the existing user read"],["Protected roles",protectedRoles,"Administrator safeguards apply"],["Privilege assignments",privilegeAssignments,"Enabled strict boolean fields"]].map(([label,value,helper])=><article key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{String(label)}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{String(value)}</p><p className="mt-1 text-xs text-slate-500">{String(helper)}</p></article>)}</section>
  <section aria-labelledby="role-filters" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 id="role-filters" className="text-sm font-semibold text-slate-950">Search and filters</h2><p className="mt-1 text-xs text-slate-500">Filter the loaded role inventory without additional database reads.</p></div><p className="text-sm font-medium text-slate-600">{filtered.length} of {roles.length} roles</p></div><form onSubmit={event=>{event.preventDefault();apply()}} className="mt-4 grid gap-3 md:grid-cols-[minmax(0,1fr)_13rem_13rem_auto]"><label className="text-sm font-medium">Search<span className="sr-only"> by role name or description</span><div className="relative mt-1.5"><Search className="pointer-events-none absolute left-3 top-3.5 size-4 text-slate-400" aria-hidden="true"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Role name or description" className={`${fieldClass} pl-9`}/></div></label><label className="text-sm font-medium">Role classification<select value={scope} onChange={event=>setScope(event.target.value as ScopeFilter)} className={`mt-1.5 ${fieldClass}`}><option value="all">All classifications</option><option value="assignable">Assignable</option><option value="legacy">Legacy read-only</option><option value="privilege_only">Privilege only</option><option value="unknown">Unknown</option></select></label><label className="text-sm font-medium">Privilege coverage<select value={privileges} onChange={event=>setPrivileges(event.target.value)} className={`mt-1.5 ${fieldClass}`}><option value="all">All coverage</option><option value="yes">Has enabled privileges</option><option value="none">Zero enabled privileges</option></select></label><div className="flex items-end gap-2"><button type="submit" className="inline-flex min-h-11 items-center rounded-xl bg-indigo-700 px-4 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-indigo-500">Apply Filters</button><button type="button" onClick={clear} aria-label="Clear role filters" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 px-3 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-indigo-500"><X className="size-4" aria-hidden="true"/>Clear</button></div></form></section>
  <p className="sr-only" aria-live="polite">{filtered.length} roles shown.</p>
  {!roles.length?<AdminEmptyState title="No roles configured" description="No existing user role values or privilege role fields were found."/>:!filtered.length?<section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-semibold">No roles match these filters</h2><p className="mt-2 text-sm text-slate-600">Adjust the criteria or clear the filters to return to the complete loaded inventory.</p><button type="button" onClick={clear} className="mt-4 min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500">Clear Filters</button></section>:<RoleResults roles={filtered}/>} 
  <aside className="rounded-xl border border-indigo-100 bg-indigo-50 p-3 text-sm text-indigo-950"><strong>Protected access:</strong> Super Admin privilege changes remain subject to the existing final-administrator safeguards. Role creation, rename, and deletion are unavailable.</aside>
 </div>
}

function RoleResults({roles}:{roles:AdminRoleSummary[]}){return <section aria-label="Role results"><div className="hidden overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm md:block"><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Role","Classification","Users","Enabled privileges","Protection","Actions"].map(label=><th key={label} scope="col" className="border-b border-slate-200 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-600">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{roles.map(role=><RoleRow key={role.role} role={role}/>)}</tbody></table></div></div><div className="grid gap-3 md:hidden">{roles.map(role=><RoleCard key={role.role} role={role}/>)}</div></section>}
function RoleIdentity({role}:{role:AdminRoleSummary}){const definition=administratorRoleDefinition(role.role);return <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="break-words font-semibold text-slate-950">{definition?.label??role.role}</span>{role.isAdministrator?<span className="rounded-full bg-red-50 px-2 py-1 text-xs font-semibold text-red-800 ring-1 ring-red-200">Protected role</span>:null}</div>{definition&&definition.label!==role.role?<code className="mt-1 block break-all text-xs text-slate-500">{role.role}</code>:null}<p className="mt-1 max-w-xl text-xs leading-5 text-slate-600">{description(role)}</p></div>}
function ScopeBadge({role}:{role:AdminRoleSummary}){const state=administratorRoleContractState(role.role);return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ${badgeClass(state)}`}>{scopeLabel[state]}</span>}
function ManageLink({role}:{role:AdminRoleSummary}){return <Link href={`/home/admin/privileges?role=${encodeURIComponent(role.role)}`} aria-label={`Manage privileges for ${role.role}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-2 text-sm font-semibold text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500"><KeyRound className="size-4" aria-hidden="true"/>Manage Privileges</Link>}
function RoleRow({role}:{role:AdminRoleSummary}){return <tr className="align-top hover:bg-slate-50/70"><td className="max-w-md px-4 py-4"><RoleIdentity role={role}/></td><td className="px-4 py-4"><ScopeBadge role={role}/><p className="mt-2 text-xs text-slate-500">{role.hasPrivilegeField?"Privilege field exists":"User-only role"}</p></td><td className="px-4 py-4 font-semibold tabular-nums">{role.userCount}</td><td className="px-4 py-4"><span className="font-semibold tabular-nums">{role.enabledPageCount}</span><span className="ml-1 text-xs text-slate-500">enabled pages</span></td><td className="px-4 py-4 text-sm">{role.isAdministrator?"Final-admin safeguards":"Standard contract rules"}</td><td className="px-4 py-3"><ManageLink role={role}/></td></tr>}
function RoleCard({role}:{role:AdminRoleSummary}){return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><RoleIdentity role={role}/><div className="mt-3"><ScopeBadge role={role}/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs font-medium uppercase text-slate-500">Users</dt><dd className="mt-1 font-semibold tabular-nums">{role.userCount}</dd></div><div><dt className="text-xs font-medium uppercase text-slate-500">Enabled privileges</dt><dd className="mt-1 font-semibold tabular-nums">{role.enabledPageCount}</dd></div><div className="col-span-2"><dt className="text-xs font-medium uppercase text-slate-500">Contract</dt><dd className="mt-1 break-words">{role.hasPrivilegeField?"Privilege field exists":"No matching privilege field"}</dd></div></dl><div className="mt-3 border-t border-slate-100 pt-2"><ManageLink role={role}/></div></article>}
