import type { AdminUserRecord } from "./admin-types";
export const ADMIN_USER_SORTS = ["name", "email", "role", "status", "company", "region"] as const;
export const ADMIN_USER_PAGE_SIZES = [25, 50, 100] as const;
export type AdminUserSort = (typeof ADMIN_USER_SORTS)[number];
export interface AdminUserListParams { query: string; role: string; status: string; company: string; region: string; sort: AdminUserSort; direction: "asc" | "desc"; page: number; pageSize: number }
export interface AdminUserListResult { users: AdminUserRecord[]; params: AdminUserListParams; totalCount: number; filteredCount: number; pageCount: number; rangeStart: number; rangeEnd: number }
type SearchValue = string | string[] | undefined;
export type AdminUserListSearchParams = Record<string, SearchValue>;
const first = (value: SearchValue) => Array.isArray(value) ? value[0] : value;
const clean = (value: SearchValue) => typeof first(value) === "string" ? first(value)!.trim() : "";
const positiveInteger = (value: SearchValue, fallback: number) => { const parsed = Number.parseInt(clean(value), 10); return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : fallback; };
export function parseAdminUserListParams(params: AdminUserListSearchParams = {}): AdminUserListParams { const sort = clean(params.sort); const pageSize = positiveInteger(params.pageSize, 25); return { query: clean(params.q).slice(0, 100), role: clean(params.role), status: clean(params.status), company: clean(params.company), region: clean(params.region), sort: ADMIN_USER_SORTS.includes(sort as AdminUserSort) ? sort as AdminUserSort : "name", direction: clean(params.direction) === "desc" ? "desc" : "asc", page: positiveInteger(params.page, 1), pageSize: ADMIN_USER_PAGE_SIZES.includes(pageSize as 25 | 50 | 100) ? pageSize : 25 }; }
const normalized = (value: unknown) => String(value ?? "").trim().toLocaleLowerCase("en-US");
const compareText = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
function matches(user: AdminUserRecord, params: AdminUserListParams) { if (params.role && user.role !== params.role || params.status && user.status !== params.status || params.company && user.company !== params.company || params.region && user.region !== params.region) return false; if (!params.query) return true; const needle = normalized(params.query); return [user.name, user.email, user.uid, user.role, user.status, user.company, user.region].some((value) => normalized(value).includes(needle)); }
export function buildAdminUserList(users: AdminUserRecord[], requestedParams: AdminUserListSearchParams = {}): AdminUserListResult { const params = parseAdminUserListParams(requestedParams); const direction = params.direction === "desc" ? -1 : 1; const filtered = users.filter((user) => matches(user, params)).sort((left, right) => { const primary = compareText(normalized(left[params.sort]), normalized(right[params.sort])); return primary === 0 ? compareText(left.key, right.key) : primary * direction; }); const pageCount = Math.max(1, Math.ceil(filtered.length / params.pageSize)); const page = Math.min(params.page, pageCount); const start = (page - 1) * params.pageSize; return { users: filtered.slice(start, start + params.pageSize), params: { ...params, page }, totalCount: users.length, filteredCount: filtered.length, pageCount, rangeStart: filtered.length ? start + 1 : 0, rangeEnd: Math.min(start + params.pageSize, filtered.length) }; }
export function adminUserFilterOptions(users: AdminUserRecord[]) { const values = (field: "company" | "region") => [...new Set(users.map((user) => user[field]).filter((value): value is string => Boolean(value)))].sort((left, right) => compareText(normalized(left), normalized(right))); return { companies: values("company"), regions: values("region") }; }
