import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {buildAdministratorAuditList,compareAdministratorAuditSnapshots,mapAdministratorAuditRecord,parseAdministratorAuditQuery} from "../../src/features/admin/administrator-audit-center.mjs";
const raw=(id,timestamp,extra={})=>mapAdministratorAuditRecord(id,{auditId:id,timestamp,administratorIdentifier:"admin-1",administratorEmail:"admin@example.com",action:"user.deactivated",resourceType:"user",resourceIdentifier:`user-${id}`,summary:"Deactivated account",before:{status:"Active"},after:{status:"Not Active"},requestIdentifier:`request-${id}`,...extra});const records=[raw("b","2026-07-02T10:00:00.000Z"),raw("a","2026-07-02T10:00:00.000Z"),raw("c","2026-07-03T10:00:00.000Z",{action:"user.invited",administratorIdentifier:"admin-2",administratorEmail:"second@example.com"})];
test("query defaults and malformed values normalize safely",()=>{assert.deepEqual(parseAdministratorAuditQuery({sort:"raw",direction:"sideways",page:"-2",pageSize:"999",dateFrom:"bad"}),{q:"",action:"",resourceType:"",administrator:"",dateFrom:"",dateTo:"",sort:"timestamp",direction:"desc",page:1,pageSize:25});});
test("default and ascending sorts use deterministic audit ID tie breaker",()=>{assert.deepEqual(buildAdministratorAuditList(records).items.map(x=>x.auditId),["c","a","b"]);assert.deepEqual(buildAdministratorAuditList(records,{direction:"asc"}).items.map(x=>x.auditId),["a","b","c"]);});
test("contains search is case-insensitive and display-field only",()=>{assert.deepEqual(buildAdministratorAuditList(records,{q:"SECOND@EXAMPLE"}).items.map(x=>x.auditId),["c"]);assert.equal(buildAdministratorAuditList(records,{q:"Not Active"}).totalItems,0);});
test("action resource administrator and date filters combine",()=>{const result=buildAdministratorAuditList(records,{action:"user.deactivated",resourceType:"user",administrator:"admin-1",dateFrom:"2026-07-02",dateTo:"2026-07-02"});assert.deepEqual(result.items.map(x=>x.auditId),["a","b"]);});
test("page size validation boundaries and empty results are stable",()=>{const many=Array.from({length:27},(_,i)=>raw(String(i).padStart(2,"0"),`2026-07-${String((i%9)+1).padStart(2,"0")}T00:00:00.000Z`));const page=buildAdministratorAuditList(many,{page:"2",pageSize:"25"});assert.equal(page.items.length,2);assert.equal(page.hasPreviousPage,true);assert.equal(page.hasNextPage,false);assert.equal(buildAdministratorAuditList(records,{q:"missing"}).totalItems,0);});
test("mapping omits raw fields, sanitizes snapshots, and tolerates malformed legacy records",()=>{const mapped=mapAdministratorAuditRecord("legacy",{auditId:"legacy",password:"hidden",before:{token:"hidden",safe:"yes"},after:null});assert.equal(mapped.malformed,true);assert.deepEqual(mapped.before,{safe:"yes"});assert.deepEqual(mapped.after,{});assert.equal("password" in mapped,false);});
test("snapshot comparison classifies added removed changed and unchanged",()=>{assert.deepEqual(compareAdministratorAuditSnapshots({removed:1,changed:1,same:true},{added:2,changed:2,same:true}).map(x=>[x.key,x.state]),[["added","added"],["changed","changed"],["removed","removed"],["same","unchanged"]]);});
test("routes authorize before audit reads and repositories are read only",async()=>{const list=await read("app/home/admin/audit/page.tsx"),detail=await read("app/home/admin/audit/[auditId]/page.tsx"),repo=await read("server/audit/firebase-audit-center-repository.ts");for(const page of [list,detail])assert.ok(page.indexOf("resolveAdministrator()")<page.indexOf("new FirebaseAuditCenterRepository"));assert.match(repo,/once\("value"\)/);assert.doesNotMatch(repo,/\.set\(|\.update\(|\.remove\(|recordAdministratorAudit/);});
test("list and detail expose responsive accessible read-only presentation",async()=>{const workspace=await read("components/audit/audit-center-workspace.tsx"),detail=await read("app/home/admin/audit/[auditId]/page.tsx");assert.match(workspace,/aria-label="Audit filters"/);assert.match(workspace,/<table/);assert.match(workspace,/lg:hidden/);assert.match(workspace,/View details/);assert.match(workspace,/Clear filters/);assert.match(workspace,/Before \/ after comparison/);assert.doesNotMatch(detail,/textarea|contentEditable|method="POST"/);});
test("audit reads do not create recursive audit entries",async()=>{for(const path of ["app/home/admin/audit/page.tsx","app/home/admin/audit/[auditId]/page.tsx","server/admin/firebase-administrator-audit-read-repository.ts"])assert.doesNotMatch(await read(path),/recordAdministratorAudit|\.append\(/);});
function read(path){return readFile(new URL(`../../src/${path}`,import.meta.url),"utf8");}
