import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { administratorRoleContractState } from "../../src/features/admin/administrator-role-contract.mjs";
const read=path=>fs.readFileSync(path,"utf8");

test("role classifications reuse the centralized exact contract",()=>{assert.equal(administratorRoleContractState("super_admin"),"assignable");assert.equal(administratorRoleContractState("project manager"),"legacy");assert.equal(administratorRoleContractState("project_owner"),"privilege_only");assert.equal(administratorRoleContractState("unexpected"),"unknown")});
test("authorized server route and denied behavior remain unchanged",()=>{const page=read("src/app/home/admin/roles/page.tsx");assert.match(page,/resolveAdministrator/);assert.match(page,/redirect\("\/login"\)/);assert.match(page,/AdminPermissionDenied/);assert.match(page,/listRoles\(\)/)});
test("page has compact header, authoritative KPIs, URL search and supported filters",()=>{const source=read("src/components/admin/admin-roles-client.tsx");for(const value of ["Manage access roles and review privilege coverage","Total roles","Roles with users","Protected roles","Privilege assignments","Search and filters","Apply Filters","Clear role filters","useSearchParams","router.push"])assert.match(source,new RegExp(value))});
test("desktop table and mobile cards preserve privilege action",()=>{const source=read("src/components/admin/admin-roles-client.tsx");for(const value of ["Role results","<table","hidden overflow-hidden","md:hidden","RoleCard","Manage Privileges","/home/admin/privileges\\?role="])assert.match(source,new RegExp(value))});
test("protected and compatibility roles have textual non-color-only indicators",()=>{const source=read("src/components/admin/admin-roles-client.tsx");for(const value of ["Protected role","Final-admin safeguards","Legacy read-only","Privilege only","User-only role","Role creation, rename, and deletion are unavailable"])assert.match(source,new RegExp(value))});
test("loading, empty, filtered-empty, error and denied states are safe",()=>{const source=read("src/components/admin/admin-roles-client.tsx"),loading=read("src/app/home/admin/roles/loading.tsx"),error=read("src/app/home/admin/error.tsx");assert.match(source,/No roles configured/);assert.match(source,/No roles match these filters/);assert.match(loading,/aria-busy="true"/);assert.match(loading,/motion-reduce:animate-none/);assert.match(error,/No data was changed/);assert.doesNotMatch(source+loading+error,/FirebaseError|databaseURL|stack trace/)});
test("accessibility and overflow boundaries are explicit",()=>{const source=read("src/components/admin/admin-roles-client.tsx");assert.match(source,/aria-live="polite"/);assert.match(source,/scope="col"/);assert.match(source,/aria-label={`Manage privileges/);assert.match(source,/overflow-x-auto/);assert.match(source,/break-all/);assert.match(source,/min-h-11/);assert.match(source,/focus-visible:ring-2/)});
test("redesign adds no delete, role mutation, API, or Firebase contract",()=>{const source=read("src/components/admin/admin-roles-client.tsx"),api=read("src/app/api/admin/roles/route.ts"),repository=read("src/server/admin/firebase-admin-data-repository.ts");assert.doesNotMatch(source,/Delete Role|Add Role|Edit Role|fetch\(/);assert.match(api,/export async function GET/);assert.doesNotMatch(api,/export async function (POST|PUT|PATCH|DELETE)/);assert.match(repository,/listRoles/)});
test("existing final-administrator protections remain server-side",()=>{const command=read("src/server/admin/admin-command-service.ts").toLowerCase();assert.match(command,/final active administrator cannot be demoted/);assert.match(command,/final administrator access cannot be removed/);assert.doesNotMatch(read("src/components/admin/admin-roles-client.tsx"),/canAdministrate|super_admin.*bypass/)});
