import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {ADMINISTRATOR_ROLE_DEFINITIONS,administratorAssignableRoleIds,administratorRoleContractState,administratorRoleDefinition,administratorRoleLabel,administratorRoleWriteError} from "../../src/features/admin/administrator-role-contract.mjs";import {buildAdminUserDetail} from "../../src/features/admin/admin-user-detail.mjs";
const ids=["field_team","l0_rno","l1_rno","l2_rno","manager","project_admin","super_admin"];
test("role definitions have unique deterministic identifiers and labels",()=>{assert.equal(new Set(ADMINISTRATOR_ROLE_DEFINITIONS.map(x=>x.id)).size,ADMINISTRATOR_ROLE_DEFINITIONS.length);assert.deepEqual(administratorAssignableRoleIds(),ids);assert.ok(ADMINISTRATOR_ROLE_DEFINITIONS.every(x=>x.label));});
test("privilege-only and legacy values are non-assignable",()=>{for(const id of ["project manager","project_owner","web_admin"])assert.ok(administratorRoleWriteError(id));assert.equal(administratorRoleContractState("project manager"),"legacy");assert.equal(administratorRoleContractState("project_owner"),"privilege_only");});
test("privilege mapping is exact and aliases are not inferred",()=>{for(const id of ids)assert.equal(administratorRoleDefinition(id).privilegeKey,id);assert.equal(administratorRoleDefinition("project manager").privilegeKey,null);assert.equal(administratorRoleDefinition("project_manager"),null);assert.equal(administratorRoleWriteError("unknown"),"Role is unknown and cannot be assigned.");});
test("known role labels preserve exact identifiers separately",()=>{for(const id of [...ids,"project manager","project_owner","web_admin"])assert.ok(administratorRoleLabel(id).length>0);});
test("strict privilege detail mapping grants only boolean true",()=>{const user=role=>({key:"u",malformed:false,uid:"uid",email:"u@example.com",name:"U",role,status:"Active"}),record=value=>[{key:"p",page_name:"Page",path:"/page",category:null,parent:null,roleValues:{manager:value}}];assert.equal(buildAdminUserDetail(user("manager"),record(true),{}).privileges[0].enabled,true);assert.equal(buildAdminUserDetail(user("manager"),record(false),{}).privileges[0].enabled,false);assert.equal(buildAdminUserDetail(user("manager"),record("true"),{}).privileges[0].enabled,false);assert.equal(buildAdminUserDetail(user("manager"),record(1),{}).privileges[0].enabled,false);assert.equal(buildAdminUserDetail(user("unknown"),record(true),{}).privileges[0].enabled,null);});
test("legacy existing users render safely without privilege aliasing",()=>{const detail=buildAdminUserDetail({key:"u",malformed:false,uid:"uid",email:"u@example.com",name:"U",role:"project manager",status:"Active"},[],{});assert.equal(detail.roleContractState,"legacy");assert.equal(detail.mappedPrivilegeKey,null);assert.ok(detail.warnings.some(x=>x.includes("legacy")));});
test("User Management and invitation share centralized assignable roles",async()=>{const page=await read("app/home/admin/users/page.tsx"),invitation=await read("server/admin/user-invitation-service.ts"),command=await read("server/admin/admin-command-service.ts");assert.match(page,/administratorAssignableRoleIds\(\)/);assert.match(invitation,/administratorAssignableRoleIds\(\)/);assert.match(command,/administratorRoleWriteError/);assert.ok(command.indexOf("administratorRoleWriteError")<command.indexOf("recordAdministratorAudit"));});
test("authorization remains exact super_admin plus strict true",async()=>{const auth=await read("features/admin/admin-authorization.mjs"),assignment=await read("features/assignment/assignment-privilege.mjs");assert.match(auth,/user\.role !== ADMINISTRATOR_ROLE/);assert.match(auth,/record\[ADMINISTRATOR_ROLE\] === true/);assert.match(assignment,/record\[role\] === true/);});
test("role audit preserves exact before and after values and rejected roles audit nothing",async()=>{const source=await read("server/admin/admin-command-service.ts");assert.match(source,/\{ role: target\.role \}/);assert.match(source,/\{ role: input\.role \}/);assert.ok(source.indexOf("administratorRoleWriteError(input.role)")<source.indexOf("updateUserRoleField"));assert.ok(source.indexOf("administratorRoleWriteError(input.role)")<source.indexOf('"user.role.changed"'));});
function read(path){return readFile(new URL(`../../src/${path}`,import.meta.url),"utf8");}
