import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
test("deactivation updates only RTDB status and revokes existing sessions",async()=>{const source=await read("server/admin/user-account-lifecycle-service.ts");assert.ok(source.indexOf("updateUserStatusField")<source.indexOf("auth.revoke"));assert.match(source,/desiredInactive&&target\.uid/);assert.doesNotMatch(source,/setDisabled|deleteUser/);});
test("reactivation preserves Firebase Auth account, password, UID, and profile",async()=>{const source=await read("server/admin/user-account-lifecycle-service.ts");assert.match(source,/desiredInactive=input\.status==="Not Active"/);assert.match(source,/user\.reactivated/);assert.doesNotMatch(source,/password|deleteUser|createUser|setDisabled/);});
test("standalone session revocation uses Firebase refresh-token revocation",async()=>{const service=await read("server/admin/user-account-lifecycle-service.ts"),gateway=await read("server/admin/firebase-account-lifecycle-auth.ts");assert.match(service,/user\.session\.revoked/);assert.match(gateway,/revokeRefreshTokens\(uid\)/);});
test("RTDB failure is surfaced and prevents audit",async()=>{const source=await read("server/admin/user-account-lifecycle-service.ts");assert.match(source,/application status could not be updated/);assert.ok(source.lastIndexOf("updateUserStatusField")<source.lastIndexOf("recordAdministratorAudit"));});
test("final administrator and confirmation protections remain server-side",async()=>{const source=await read("server/admin/user-account-lifecycle-service.ts");assert.match(source,/countActiveAdministrators\(\)<=1/);assert.match(source,/final active administrator cannot be deactivated/);assert.match(source,/input\.confirmed!==true/);});
test("self session revocation requires explicit confirmation",async()=>{const source=await read("server/admin/user-account-lifecycle-service.ts");assert.match(source,/uid===context\.actorUid&&input\.confirmSelf!==true/);});
test("all lifecycle actions reuse safe administrator audit",async()=>{const source=await read("server/admin/user-account-lifecycle-service.ts");assert.match(source,/recordAdministratorAudit/);for(const action of ["user.deactivated","user.reactivated","user.session.revoked"])assert.match(source,new RegExp(action.replaceAll(".","\\.")));assert.match(source,/before:\{status:target\.status\}/);assert.match(source,/after:\{status:input\.status\}/);});
test("lifecycle routes authorize before body parsing and service calls",async()=>{for(const path of ["status","sessions"]){const source=await read(`app/api/admin/users/[userKey]/${path}/route.ts`);assert.ok(source.indexOf("resolveAdministrator()")<source.indexOf("request.json()"));}});
test("desktop and mobile controls use an accessible confirmation dialog",async()=>{const users=await read("components/admin/admin-users-client.tsx"),dialog=await read("components/admin/admin-session-revocation-button.tsx");assert.match(users,/confirmed: true/);assert.match(dialog,/role="dialog"/);assert.match(dialog,/aria-modal="true"/);});
function read(path){return readFile(new URL(`../../src/${path}`,import.meta.url),"utf8")}