import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {validateUserInvitation} from "../../src/features/admin/user-invitation-contract.mjs";
const valid={name:" Ada Lovelace ",email:" ADA@EXAMPLE.COM ",role:"manager",company:"Radaba",department:"Operations",region:"West",phone:"123"},roles=["manager","super_admin"];
test("invitation validation normalizes a successful invitation",()=>{assert.deepEqual(validateUserInvitation(valid,roles),{success:true,value:{...valid,name:"Ada Lovelace",email:"ada@example.com",company:"Radaba",department:"Operations",region:"West",phone:"123"}});});
test("invitation rejects malformed email, invalid role, and missing required fields",()=>{const result=validateUserInvitation({email:"bad",role:"unknown"},roles);assert.equal(result.success,false);assert.deepEqual(Object.keys(result.errors).sort(),["company","department","email","name","region","role"]);});
test("provisioning checks duplicate email in Auth and RTDB",async()=>{const source=await read("server/admin/user-invitation-service.ts");assert.match(source,/repository\.emailExists\(input\.email\)/);assert.match(source,/auth\.emailExists\(input\.email\)/);assert.match(source,/A user with this email already exists/);});
test("successful provisioning creates Auth then RTDB with Active status and no password response",async()=>{const service=await read("server/admin/user-invitation-service.ts"),gateway=await read("server/admin/firebase-user-invitation-gateways.ts");assert.ok(service.indexOf("this.auth.create")<service.indexOf("this.repository.create"));assert.match(gateway,/status:"Active"/);assert.doesNotMatch(service,/return \{[^}]*password/);});
test("Auth and RTDB failures produce explicit administrator errors",async()=>{const source=await read("server/admin/user-invitation-service.ts");assert.match(source,/Firebase Authentication could not create the user/);assert.match(source,/application profile could not be created/i);});
test("RTDB failure deletes the new Auth account and surfaces failed compensation",async()=>{const source=await read("server/admin/user-invitation-service.ts");assert.ok(source.indexOf("repository.create")<source.indexOf("auth.remove"));assert.match(source,/Provisioning partially completed/);assert.match(source,/requestIdentifier/);});
test("invitation records the generic safe administrator audit",async()=>{const source=await read("server/admin/user-invitation-service.ts");assert.match(source,/recordAdministratorAudit/);assert.match(source,/action:\s*"user\.invited"/);assert.match(source,/before:\s*\{\}/);assert.doesNotMatch(source,/after:\s*\{[^}]*password/);});
test("POST authorizes before parsing or provisioning and UI exposes accessible fields",async()=>{const route=await read("app/api/admin/users/route.ts"),ui=await read("components/admin/admin-user-invite-dialog.tsx");assert.ok(route.indexOf("resolveAdministrator()")<route.indexOf("request.json()"));for(const name of ["name","email","role","company","department","region","phone"])assert.match(ui,new RegExp(`name=\"${name}\"`));assert.match(ui,/role="dialog"/);assert.match(ui,/role="alert"/);});
function read(path){return readFile(new URL(`../../src/${path}`,import.meta.url),"utf8");}
