import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { buildUserDeletePreview } from "../../src/features/admin/user-delete-preview.mjs";
const user={key:"user-key",uid:"uid-1",email:"person@example.com",name:"Person",role:"manager",status:"Active"};
test("dependency counts are correct and dependencies block deletion",()=>{const result=buildUserDeletePreview(user,{assignment:{a:{rigger_email:user.email,work_report:{findings:"x"}}},cell:{c:{updated_by_uid:user.uid}},image:{i:{uploaded_by_uid:user.uid}},assignment_photo:{a:{p:{uploaded_by_uid:user.uid}}},administrator_audit:{x:{administratorIdentifier:user.uid}},assignment_audit:{a:{x:{actor_uid:user.uid}}},tower_audit:{},log:{l:{email:user.email}}});assert.deepEqual(result.counts,{assignments:1,cells:1,images:2,auditRecords:2,reports:1,profile:0,loginHistory:1});assert.equal(result.deletionAllowed,false);});
test("zero dependencies report deletable and preview is pure",()=>{const data={assignment:{a:{rigger_email:"other@example.com"}}};const before=structuredClone(data);const result=buildUserDeletePreview(user,data);assert.equal(result.dependencyCount,0);assert.equal(result.deletionAllowed,true);assert.deepEqual(data,before);});
test("inactive login is rejected with administrator guidance and active login remains accepted",async()=>{const source=await read("services/authentication/auth.ts");assert.match(source,/\["not active", "inactive"\]/);assert.match(source,/Your account has been deactivated\. Please contact an administrator\./);assert.doesNotMatch(source,/status\.trim\(\)\.toLowerCase\(\) === "active"/);});
test("status transition changes only RTDB status, revokes sessions, audits, and never deletes Auth",async()=>{const source=await read("server/admin/user-account-lifecycle-service.ts");assert.match(source,/updateUserStatusField/);assert.match(source,/user\.deactivated/);assert.match(source,/user\.reactivated/);assert.match(source,/before:\{status:target\.status\}/);assert.match(source,/after:\{status:input\.status\}/);assert.doesNotMatch(source,/setDisabled|deleteUser|\.remove\(/);});
test("preview route is authorized, GET-only, and contains no mutation",async()=>{const source=await read("app/api/admin/users/[userKey]/delete-preview/route.ts");assert.ok(source.indexOf("resolveAdministrator()")<source.indexOf("findUser"));assert.match(source,/export async function GET/);assert.doesNotMatch(source,/export async function (POST|PATCH|DELETE)|\.set\(|\.update\(|\.remove\(/);});
test("users UI exposes lifecycle actions, preview warning, and status filter",async()=>{const [users,dialog]=await Promise.all([read("components/admin/admin-users-client.tsx"),read("components/admin/user-delete-preview-dialog.tsx")]);for(const label of ["View","Edit","Change Role","Deactivate","Activate","Reset Password","Delete Preview"])assert.match(users,new RegExp(label));assert.match(users,/name="status"/);assert.match(dialog,/Deletion is not implemented in this milestone/);assert.match(dialog,/Deletion allowed\?/);});
function read(path){return readFile(new URL(`../../src/${path}`,import.meta.url),"utf8")}