/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { AlertTriangle, ArrowLeft, ExternalLink, ImageOff } from "lucide-react";
import { PageHeader } from "@/components/application-shell/page-header";
import { extractEmbeddedImages } from "@/features/cells-images/embedded-image-contract";
import type { CellRecord, TowerVisitRecord } from "@/features/cells-images/cells-images-types";

const text=(value:unknown)=>String(value??"").trim();
const show=(value:unknown)=>text(value)||"—";
const Field=({label,value}:{label:string;value:unknown})=><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm text-slate-900">{show(value)}</dd></div>;
const Section=({title,items}:{title:string;items:[string,unknown][]})=><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-semibold">{title}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(([label,value])=><Field key={label} label={label} value={value}/>)}</dl></section>;
export function CellEngineeringWorkspace({cell,tower}:{cell:CellRecord;tower:TowerVisitRecord|null}) {
  const images=extractEmbeddedImages({sourceRecordType:"cell",sourceRecordKey:cell.databaseKey,record:cell});
  const events=[["Submitted",cell.submitted_at??cell.created_datetime],["Updated",cell.updated_at??cell.updated_datetime],["Closed",cell.closed_datetime??cell.closed_date]].filter(([,value])=>text(value));
  return <div className="space-y-5">
    <PageHeader title={show(cell.rcell_id)} description="Read-only Cell engineering workspace." actions={<div className="flex flex-wrap gap-2"><Link href="/home/cells" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500"><ArrowLeft className="size-4" aria-hidden="true"/>Back to Cells</Link>{text(cell.assignment_id)?<Link className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-4 text-sm font-semibold text-indigo-700 focus-visible:ring-2" href={`/home/assignment?${new URLSearchParams({q:text(cell.assignment_id)})}`}>Open Assignment</Link>:null}</div>}/>
    {!tower&&text(cell.tower_id)?<p role="status" className="flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle className="size-4" aria-hidden="true"/>The referenced Tower could not be resolved. Persisted Cell context is shown.</p>:null}
    <div className="grid gap-4 xl:grid-cols-2">
      <Section title="Cell Identification" items={[["Database key",cell.databaseKey],["RCell ID",cell.rcell_id],["Assignment ID",cell.assignment_id],["Sector",cell.sector],["Band",cell.band]]}/>
      <Section title="Tower Information" items={[["Tower ID",cell.tower_id??tower?.tower_id],["Site name",cell.sitename??tower?.sitename],["Region",cell.region??tower?.region],["Province",cell.province??tower?.province],["Kabupaten",cell.kabupaten??tower?.kabupaten],["Kecamatan",cell.kecamatan??tower?.kecamatan]]}/>
      <Section title="Ownership" items={[["Company",cell.company],["Coordinator",cell.coordinator_name],["Coordinator email",cell.coordinator_email],["Rigger",cell.rigger_name],["Rigger email",cell.rigger_email],["RNO",cell.rno_name],["RNO email",cell.rno_email]]}/>
      <Section title="Antenna" items={[["Type",cell.antenna_type],["Serial",cell.antenna_serial_number],["Height",cell.antenna_height],["Port quantity",cell.antenna_port_quantity],["Ports in use",cell.antenna_port_in_use],["AISG",cell.antenna_port_aisg_cable],["Notes",cell.antenna_port_note]]}/>
      <Section title="RRU" items={[["Type",cell.rru_type],["Serial",cell.rru_serial_number]]}/>
      <Section title="Alignment" items={[["Azimuth before",cell.azimuth_before],["Azimuth after",cell.azimuth_after],["Electrical tilt before",cell.electrical_tilt_before],["Electrical tilt after",cell.electrical_tilt_after],["Mechanical tilt before",cell.mechanical_tilt_before],["Mechanical tilt after",cell.mechanical_tilt_after]]}/>
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-labelledby="cell-images"><h2 id="cell-images" className="font-semibold">Images</h2>{images.length?<div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">{images.map((image)=><article key={image.id} className="overflow-hidden rounded-xl border"><div className="aspect-square bg-slate-100">{image.url?<img src={image.url} alt={`${image.category} for ${show(cell.rcell_id)}`} loading="lazy" referrerPolicy="no-referrer" className="size-full object-cover"/>:<div className="flex size-full items-center justify-center"><ImageOff className="size-8 text-slate-400" aria-hidden="true"/></div>}</div><div className="p-3"><h3 className="text-sm font-semibold">{image.category}</h3><p className="mt-1 text-xs text-slate-500">{image.dataQuality}</p>{image.url?<a href={image.url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-10 items-center font-semibold text-indigo-700 focus-visible:ring-2">Open original</a>:null}</div></article>)}</div>:<div className="mt-4 rounded-xl border border-dashed p-8 text-center"><ImageOff className="mx-auto size-8 text-slate-400" aria-hidden="true"/><h3 className="mt-2 font-semibold">No Related Images</h3><p className="mt-1 text-sm text-slate-500">This Cell record contains no supported embedded image fields.</p></div>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Timeline</h2>{events.length?<ol className="mt-4 space-y-3">{events.map(([label,value])=><li key={String(label)} className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-indigo-600"/><div><h3 className="text-sm font-semibold">{String(label)}</h3><p className="text-sm text-slate-600">{show(value)}</p></div></li>)}</ol>:<p className="mt-3 text-sm text-slate-500">No submitted, updated, or closed timestamp is stored.</p>}</section>
    {text(cell.tower_id)?<Link className="inline-flex min-h-11 items-center gap-2 font-semibold text-indigo-700 focus-visible:ring-2" href={`/home/towers?${new URLSearchParams({q:text(cell.tower_id)})}`}>Open Tower <ExternalLink className="size-4" aria-hidden="true"/></Link>:null}
  </div>;
}
