"use client";
import Link from "next/link";
import { ArrowLeft,Download,ExternalLink,FileWarning } from "lucide-react";
import { PageHeader } from "@/components/application-shell/page-header";
import type { AorReportRecord } from "@/features/report/aor-report-types";
const show=(value:unknown)=>String(value??"").trim()||"Not available";
export function ReportDetail({report}:{report:AorReportRecord}){const usable=report.qualityStatus==="valid"&&report.downloadUrl;const rows:[string,unknown][]=[["Report ID",report.reportId],["Filename",report.fileName],["Source record type",report.sourceRecordType],["Source record key",report.sourceRecordKey],["Storage object path",report.storageObjectPath],["Closed date",report.closedDateDisplay],["Closed datetime",report.closedDateTime],["Quality status",report.qualityStatus]];
return <div className="space-y-5"><nav aria-label="Breadcrumb" className="text-sm text-slate-500"><Link href="/home/reports" className="focus-visible:ring-2">Reports</Link> / <span aria-current="page">{show(report.fileName??report.towerId)}</span></nav><PageHeader title={show(report.fileName??report.towerId)} description={`${show(report.towerId)} · ${show(report.assignmentId)}`} actions={<div className="flex flex-wrap gap-2"><Link className="action-button" href="/home/reports"><ArrowLeft className="size-4" aria-hidden="true"/>Back to Reports</Link>{usable?<><a className="action-button" href="#pdf">Preview</a><a className="action-button" href={report.downloadUrl!} target="_blank" rel="noopener noreferrer" download><Download className="size-4" aria-hidden="true"/>Download</a></>:null}<Link className="action-button" href={`/home/assignment/${encodeURIComponent(report.assignmentKey)}`}>Open Assignment</Link>{report.towerId?<Link className="action-button" href={`/home/towers?${new URLSearchParams({q:report.towerId})}`}>Open Tower</Link>:null}</div>}/>
<div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${report.qualityStatus==="valid"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{report.qualityStatus}</span><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">Assignment record</span></div>
<div className="grid gap-4 xl:grid-cols-2"><Section title="Report Information" rows={rows}/><Section title="Assignment" rows={[["Assignment ID",report.assignmentId],["Category",report.assignmentCategory],["Status",report.assignmentStatus]]}/><Section title="Tower" rows={[["Tower ID",report.towerId],["Site name",report.siteName],["Region",report.region],["Sub region",report.subRegion],["Company",report.company]]}/><Section title="People" rows={[["Rigger",report.riggerName],["Rigger email",report.riggerEmail],["Coordinator",report.coordinatorName],["Coordinator email",report.coordinatorEmail]]}/></div>
<section id="pdf" className="scroll-mt-24 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">PDF Preview</h2>{usable?<><p className="mt-2 text-xs text-slate-500">Browser-native preview. The authorized Storage URL is not displayed or logged.</p><iframe src={report.downloadUrl!} title={`PDF preview: ${show(report.fileName)}`} loading="lazy" referrerPolicy="no-referrer" className="mt-4 h-[70vh] min-h-96 w-full rounded-xl border bg-slate-100"/><div className="mt-4 flex flex-wrap gap-3"><a className="action-button" href={report.downloadUrl!} target="_blank" rel="noopener noreferrer"><ExternalLink className="size-4" aria-hidden="true"/>Open original</a><a className="action-button" href={report.downloadUrl!} target="_blank" rel="noopener noreferrer" download><Download className="size-4" aria-hidden="true"/>Download PDF</a></div></>:<div className="mt-4 rounded-xl border border-dashed p-10 text-center"><FileWarning className="mx-auto size-10 text-amber-600" aria-hidden="true"/><h3 className="mt-3 font-semibold">PDF unavailable</h3><p className="mt-2 text-sm text-slate-600">The report URL is missing, malformed, outside the report folder, or not a PDF.</p></div>}</section>
<section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Data Quality</h2>{report.warnings.length?<ul className="mt-3 space-y-2">{report.warnings.map(warning=><li className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900" key={warning}>{warning.replaceAll("-"," ")}</li>)}</ul>:<p className="mt-2 text-sm text-slate-600">No configured metadata warning was detected. Storage object existence is not fetched by this page.</p>}</section></div>}
function Section({title,rows}:{title:string;rows:[string,unknown][]}){return <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">{title}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{rows.map(([label,value])=><div key={label}><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm">{show(value)}</dd></div>)}</dl></section>}
