"use client";
import Link from "next/link";
import { useState,useTransition } from "react";
import { usePathname,useRouter,useSearchParams } from "next/navigation";
import { Columns3,Download,Eye,FileText,RefreshCw,RotateCcw,Search } from "lucide-react";
import { PageHeader } from "@/components/application-shell/page-header";
import { reportExportRows } from "@/features/report/aor-report-contract";
import type { ReportFilters,ReportsPage,AorReportRecord } from "@/features/report/aor-report-types";
const show=(value:unknown)=>String(value??"").trim()||"—",csv=(value:unknown)=>{let raw=String(value??"");if(/^[=+\-@]/.test(raw))raw=`'${raw}`;return `"${raw.replaceAll('"','""')}"`;};
const fields=[["q","Search"],["tower","Tower"],["assignment","Assignment"],["region","Region"],["subRegion","Sub Region"],["company","Company"],["category","Assignment Category"],["coordinator","Coordinator"],["rigger","Rigger"]] as const;
export function ReportsCenter({result,filters}:{result:ReportsPage;filters:ReportFilters}){const router=useRouter(),pathname=usePathname(),params=useSearchParams(),[pending,startTransition]=useTransition(),[draft,setDraft]=useState(filters),[settings,setSettings]=useState(false);const valid=result.rows.filter(x=>x.qualityStatus==="valid").length,missing=result.rows.filter(x=>x.qualityStatus==="missing-url"||x.qualityStatus==="missing-file-name").length,broken=result.rows.filter(x=>x.qualityStatus==="invalid-url").length;
  const navigate=(next:ReportFilters)=>{const query=new URLSearchParams();Object.entries(next).forEach(([key,value])=>{if(value&&value!==1&&value!==50)query.set(key,String(value));});startTransition(()=>router.push(`${pathname}?${query}`));};
  const exportMetadata=()=>{const rows=reportExportRows(result.rows),headers=Object.keys(rows[0]??{closed_date:"",tower_id:"",assignment_id:"",rigger_name:"",coordinator_name:"",region:"",sub_region:"",company:"",assignment_category:"",filename:"",report_status:"",report_id:""});const body=[headers,...rows.map(row=>headers.map(key=>row[key]))].map(row=>row.map(csv).join(",")).join("\r\n");const blob=new Blob(["\uFEFF",body],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="aor-report-metadata.csv";a.click();URL.revokeObjectURL(a.href);};
  return <div className="space-y-5" aria-busy={pending}><PageHeader title="AOR Reports" description="Review and download completed field-operation reports." actions={<div className="flex flex-wrap gap-2"><button className="action-button" onClick={()=>startTransition(()=>router.refresh())}><RefreshCw className={`size-4 ${pending?"animate-spin":""}`} aria-hidden="true"/>Refresh</button><button className="action-button" onClick={exportMetadata}><Download className="size-4" aria-hidden="true"/>Export Metadata</button><button className="action-button" onClick={()=>setSettings(!settings)} aria-expanded={settings}><Columns3 className="size-4" aria-hidden="true"/>Column Settings</button></div>}/>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-5" aria-label="Bounded report summary">{[["Total Reports",result.filteredCount],["Valid PDF",valid],["Missing Report Files",missing],["Broken References",broken],["Recently Closed",result.rows.filter(x=>x.closedDate).length]].map(([label,value])=><article className="rounded-2xl border bg-white p-4 shadow-sm" key={label}><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">Current bounded result</p></article>)}</section>
    {settings?<p className="rounded-xl border bg-white p-4 text-sm text-slate-600">The default operational columns are shown. Technical source and object-path fields remain available on Report Detail.</p>:null}
    <section className="sticky top-16 z-10 rounded-2xl border bg-white p-4 shadow-sm"><h2 className="font-semibold">Search and filters</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{fields.map(([key,label])=><label className={key==="q"?"text-sm font-medium sm:col-span-2":"text-sm font-medium"} key={key}>{label}<input className="field-control" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value,page:1})}/></label>)}<label className="text-sm font-medium">Closed Date From<input type="date" className="field-control" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value,page:1})}/></label><label className="text-sm font-medium">Closed Date To<input type="date" className="field-control" value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value,page:1})}/></label><Select label="Has Report" value={draft.hasReport} set={hasReport=>setDraft({...draft,hasReport,page:1})} options={[["","All"],["yes","Valid report"],["no","Missing or broken"]]}/><Select label="Data Quality" value={draft.quality} set={quality=>setDraft({...draft,quality,page:1})} options={[["","All"],["valid","Valid"],["missing-url","Missing URL"],["missing-file-name","Missing filename"],["invalid-url","Invalid URL"]]}/></div><div className="mt-4 flex gap-2"><button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-indigo-700 px-4 text-sm font-semibold text-white focus-visible:ring-2" onClick={()=>navigate(draft)}><Search className="size-4" aria-hidden="true"/>Apply Filters</button><button className="action-button" onClick={()=>{const empty={...draft,q:"",tower:"",assignment:"",region:"",subRegion:"",company:"",category:"",coordinator:"",rigger:"",quality:"",hasReport:"",from:"",to:"",page:1};setDraft(empty);navigate(empty);}}><RotateCcw className="size-4" aria-hidden="true"/>Reset</button></div></section>
    <p className="sr-only" aria-live="polite">{result.rows.length} reports loaded.</p>{result.rows.length?<ReportResults rows={result.rows}/>:<section className="rounded-2xl border border-dashed bg-white p-10 text-center"><FileText className="mx-auto size-10 text-indigo-600" aria-hidden="true"/><h2 className="mt-3 font-semibold">{params.toString()?"No Search Results":"No Reports"}</h2><p className="mt-2 text-sm text-slate-600">No AOR report metadata was found in this bounded Assignment window.</p></section>}
    <nav aria-label="Report pagination" className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4"><p className="text-sm text-slate-600">Showing {result.rows.length} · scanned {result.scanned} recent Assignments</p><div className="flex gap-2">{filters.page>1?<button className="action-button" onClick={()=>navigate({...filters,page:filters.page-1})}>Previous</button>:null}{result.hasNext?<button className="action-button" onClick={()=>navigate({...filters,page:filters.page+1})}>Next</button>:null}</div></nav></div>}
function ReportResults({rows}:{rows:AorReportRecord[]}){return <section aria-label="Report results"><div className="hidden max-h-[65vh] overflow-auto rounded-2xl border bg-white lg:block"><table className="w-full min-w-[1350px] text-left text-sm"><thead className="sticky top-0 bg-slate-50"><tr>{["Closed Date","Tower ID","Assignment","Category","Company","Region","Sub Region","Coordinator","Rigger","File","Status","Actions"].map(x=><th className="border-b px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.reportId}>{[row.closedDateDisplay,row.towerId,row.assignmentId,row.assignmentCategory,row.company,row.region,row.subRegion,row.coordinatorName,row.riggerName,row.fileName,row.qualityStatus].map((value,index)=><td className="max-w-44 break-words px-3 py-3" key={index}>{show(value)}</td>)}<td className="px-3"><Actions row={row}/></td></tr>)}</tbody></table></div><div className="grid gap-4 lg:hidden">{rows.map(row=><article className="rounded-2xl border bg-white p-4 shadow-sm" key={row.reportId}><p className="text-xs font-semibold uppercase text-indigo-700">{show(row.qualityStatus)}</p><h3 className="mt-2 font-semibold">{show(row.fileName??row.towerId)}</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-sm">{[["Closed",row.closedDateDisplay],["Tower",row.towerId],["Assignment",row.assignmentId],["Category",row.assignmentCategory],["Company",row.company],["Region",row.region],["Coordinator",row.coordinatorName],["Rigger",row.riggerName]].map(([label,value])=><div key={label}><dt className="text-xs uppercase text-slate-500">{label}</dt><dd>{show(value)}</dd></div>)}</dl><div className="mt-4"><Actions row={row}/></div></article>)}</div></section>}
function Actions({row}:{row:AorReportRecord}){const usable=row.qualityStatus==="valid"&&row.downloadUrl;return <div className="flex min-w-56 flex-wrap gap-x-3"><Link className="row-link" href={`/home/reports/${row.reportId}`}><Eye className="size-4" aria-hidden="true"/>View Report</Link>{usable?<><Link className="row-link" href={`/home/reports/${row.reportId}#pdf`}>Preview PDF</Link><a className="row-link" href={row.downloadUrl!} target="_blank" rel="noopener noreferrer" download>Download PDF</a></>:<span className="text-xs text-amber-700" title="The PDF URL is missing or invalid.">PDF unavailable</span>}<Link className="row-link" href={`/home/assignment/${encodeURIComponent(row.assignmentKey)}`}>Open Assignment</Link>{row.towerId?<Link className="row-link" href={`/home/towers?${new URLSearchParams({q:row.towerId})}`}>Open Tower</Link>:null}</div>}
function Select({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:[string,string][]}){return <label className="text-sm font-medium">{label}<select className="field-control" value={value} onChange={e=>set(e.target.value)}>{options.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}
