"use client";
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useRef, useState, type DragEvent } from "react";
import { Camera, ChevronLeft, ChevronRight, Download, ImageIcon, RefreshCw, Trash2, Upload, X } from "lucide-react";
import { ASSIGNMENT_PHOTO_CATEGORIES, ASSIGNMENT_PHOTO_CATEGORY_LABELS, ASSIGNMENT_PHOTO_LIMITS, ASSIGNMENT_PHOTO_MIME_EXTENSIONS, type AssignmentPhoto, type AssignmentPhotoCategory } from "@/features/assignment/assignment-photo-contract";

type QueueItem = { id: string; file: File; progress: number; state: "queued" | "uploading" | "done" | "error"; error?: string };
const api = (assignmentId: string) => `/api/assignments/${encodeURIComponent(assignmentId)}/photos`;
async function thumbnail(file: File) {
  try {
    const bitmap = await createImageBitmap(file, { imageOrientation: "from-image" });
    const scale = Math.min(1, 480 / Math.max(bitmap.width, bitmap.height));
    const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(bitmap.width * scale)); canvas.height = Math.max(1, Math.round(bitmap.height * scale));
    canvas.getContext("2d")?.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
    return await new Promise<File | null>((resolve) => canvas.toBlob((blob) => resolve(blob ? new File([blob], "thumbnail", { type: file.type }) : null), file.type, 0.82));
  } catch { return null; }
}
export function AssignmentPhotoEvidence({ assignmentId, readOnly }: { assignmentId: string; readOnly: boolean }) {
  const [category, setCategory] = useState<AssignmentPhotoCategory>("before");
  const [photos, setPhotos] = useState<AssignmentPhoto[]>([]);
  const [queue, setQueue] = useState<QueueItem[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [viewer, setViewer] = useState<string | null>(null);
  const input = useRef<HTMLInputElement>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(api(assignmentId), { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || body.message || "Could not load photo evidence."); setPhotos(body.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load photo evidence."); } finally { setLoading(false); } }, [assignmentId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const uploadOne = useCallback(async (item: QueueItem) => {
    setQueue((items) => items.map((x) => x.id === item.id ? { ...x, state: "uploading", progress: 0, error: undefined } : x));
    const thumb = await thumbnail(item.file); const form = new FormData(); form.set("photoId", item.id); form.set("category", category); form.set("file", item.file); if (thumb) form.set("thumbnail", thumb);
    await new Promise<void>((resolve) => { const xhr = new XMLHttpRequest(); xhr.open("POST", api(assignmentId)); xhr.upload.onprogress = (event) => { if (event.lengthComputable) setQueue((items) => items.map((x) => x.id === item.id ? { ...x, progress: Math.round(event.loaded / event.total * 100) } : x)); }; xhr.onload = () => { let body: { error?: string; message?: string } = {}; try { body = JSON.parse(xhr.responseText); } catch {} if (xhr.status >= 200 && xhr.status < 300) { setQueue((items) => items.map((x) => x.id === item.id ? { ...x, state: "done", progress: 100 } : x)); resolve(); } else { setQueue((items) => items.map((x) => x.id === item.id ? { ...x, state: "error", error: body.error || body.message || "Upload failed." } : x)); resolve(); } }; xhr.onerror = () => { setQueue((items) => items.map((x) => x.id === item.id ? { ...x, state: "error", error: "Network error. Retry this photo." } : x)); resolve(); }; xhr.send(form); });
  }, [assignmentId, category]);
  const select = async (files: FileList | File[]) => {
    if (readOnly) return; const selected = Array.from(files).slice(0, ASSIGNMENT_PHOTO_LIMITS.maximumBatchFiles); const items: QueueItem[] = selected.map((file) => ({ id: crypto.randomUUID(), file, progress: 0, state: "queued" }));
    const checked = items.map((item) => !ASSIGNMENT_PHOTO_MIME_EXTENSIONS[item.file.type] ? { ...item, state: "error" as const, error: "Only JPEG, PNG, and WebP are supported." } : item.file.size > ASSIGNMENT_PHOTO_LIMITS.maximumBytes ? { ...item, state: "error" as const, error: "Image exceeds the 10 MB limit." } : item);
    setQueue(checked); for (const item of checked) if (item.state === "queued") await uploadOne(item); await load();
  };
  const visible = photos.filter((photo) => photo.category === category); const selectedPhoto = photos.find((photo) => photo.id === viewer) ?? null;
  const remove = async (photo: AssignmentPhoto) => { if (!window.confirm(`Delete ${photo.originalFilename}? This cannot be undone.`)) return; setError(""); const response = await fetch(`${api(assignmentId)}/${encodeURIComponent(photo.id)}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) { setError(body.error || body.message || "Photo could not be deleted."); return; } setViewer(null); await load(); };
  const move = (direction: number) => { if (!selectedPhoto) return; const index = visible.findIndex((photo) => photo.id === selectedPhoto.id); setViewer(visible[(index + direction + visible.length) % visible.length]?.id ?? null); };
  return <section aria-labelledby="photo-evidence-title" className="rounded-2xl border border-slate-200 bg-white shadow-sm">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-100 bg-slate-50/70 px-4 py-3 sm:px-5"><div><h2 id="photo-evidence-title" className="text-sm font-semibold text-slate-950">Photo Evidence</h2><p className="mt-1 text-xs text-slate-500">Structured field evidence retained with this Assignment.</p></div>{readOnly ? <span className="rounded-full bg-slate-200 px-3 py-1 text-xs font-semibold text-slate-700">Completed · read-only</span> : null}</header>
    <div className="p-4 sm:p-5"><div role="tablist" aria-label="Photo evidence category" className="grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1">{ASSIGNMENT_PHOTO_CATEGORIES.map((value) => <button key={value} role="tab" aria-selected={category === value} onClick={() => setCategory(value)} className={`rounded-lg px-2 py-2 text-xs font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 sm:text-sm ${category === value ? "bg-white text-indigo-700 shadow-sm" : "text-slate-600"}`}>{ASSIGNMENT_PHOTO_CATEGORY_LABELS[value]} <span className="text-slate-400">({photos.filter((photo) => photo.category === value).length})</span></button>)}</div>
      {!readOnly ? <div onDragOver={(event) => event.preventDefault()} onDrop={(event: DragEvent) => { event.preventDefault(); void select(event.dataTransfer.files); }} className="mt-4 rounded-xl border border-dashed border-indigo-300 bg-indigo-50/40 p-5 text-center"><input ref={input} className="sr-only" type="file" accept="image/*" multiple onChange={(event) => event.target.files && void select(event.target.files)} /><Camera aria-hidden="true" className="mx-auto size-6 text-indigo-600" /><p className="mt-2 text-sm font-semibold text-slate-900">Drop field photos here</p><p className="mt-1 text-xs text-slate-500">JPEG, PNG or WebP · up to 10 MB each · 10 at a time</p><button type="button" onClick={() => input.current?.click()} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-indigo-500"><Upload className="size-4" />Choose camera or gallery</button></div> : <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">Revisit this Assignment before adding or deleting evidence.</p>}
      {queue.length ? <ul aria-live="polite" aria-label="Upload progress" className="mt-4 space-y-2">{queue.map((item) => <li key={item.id} className="rounded-lg border border-slate-200 p-3"><div className="flex items-center justify-between gap-3 text-xs"><span className="truncate font-medium">{item.file.name}</span><span>{item.state === "error" ? item.error : `${item.progress}%`}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full transition-[width] motion-reduce:transition-none ${item.state === "error" ? "bg-rose-500" : "bg-indigo-600"}`} style={{ width: `${item.progress}%` }} /></div>{item.state === "error" && ASSIGNMENT_PHOTO_MIME_EXTENSIONS[item.file.type] && item.file.size <= ASSIGNMENT_PHOTO_LIMITS.maximumBytes ? <button onClick={() => void uploadOne(item).then(load)} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-indigo-700"><RefreshCw className="size-3" />Retry</button> : null}</li>)}</ul> : null}
      {error ? <div role="alert" className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div> : null}
      {loading ? <div role="status" className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{[1,2,3,4].map((n) => <div key={n} className="aspect-square animate-pulse rounded-xl bg-slate-100 motion-reduce:animate-none" />)}<span className="sr-only">Loading photo evidence</span></div> : visible.length ? <ul className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{visible.map((photo) => <li key={photo.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><button onClick={() => setViewer(photo.id)} aria-label={`View ${photo.originalFilename}`} className="block aspect-square w-full overflow-hidden bg-slate-100 focus-visible:ring-2 focus-visible:ring-indigo-500"><img src={photo.thumbnailUrl} alt={`${ASSIGNMENT_PHOTO_CATEGORY_LABELS[photo.category]} evidence: ${photo.originalFilename}`} loading="lazy" className="h-full w-full object-cover" /></button><div className="p-2"><p className="truncate text-xs font-semibold text-slate-800">{photo.originalFilename}</p><p className="mt-1 truncate text-[11px] text-slate-500">{photo.uploadedByName} · {photo.uploadedAt}</p></div></li>)}</ul> : <div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 px-5 py-8 text-center"><ImageIcon className="mx-auto size-7 text-slate-400" /><p className="mt-2 text-sm font-semibold text-slate-800">No {ASSIGNMENT_PHOTO_CATEGORY_LABELS[category].toLowerCase()} photos</p><p className="mt-1 text-xs text-slate-500">Evidence uploaded to this category will appear here.</p></div>}
    </div>{selectedPhoto ? <PhotoViewer photo={selectedPhoto} count={visible.length} onClose={() => setViewer(null)} onMove={move} onDelete={readOnly ? undefined : () => void remove(selectedPhoto)} /> : null}
  </section>;
}
function PhotoViewer({ photo, count, onClose, onMove, onDelete }: { photo: AssignmentPhoto; count: number; onClose: () => void; onMove: (direction: number) => void; onDelete?: () => void }) {
  const close = useRef<HTMLButtonElement>(null); const panel = useRef<HTMLDivElement>(null); useEffect(() => { const previous = document.activeElement as HTMLElement | null; close.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "ArrowLeft") onMove(-1); if (event.key === "ArrowRight") onMove(1); if (event.key === "Tab" && panel.current) { const controls = [...panel.current.querySelectorAll<HTMLElement>("button:not([disabled]),a[href]")]; const first = controls[0], last = controls.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); previous?.focus(); }; }, [onClose, onMove]);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/90 p-3" role="dialog" aria-modal="true" aria-label="Photo evidence viewer"><div ref={panel} className="flex max-h-full w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white"><header className="flex items-center justify-between gap-3 border-b p-3"><div><p className="text-sm font-semibold">{ASSIGNMENT_PHOTO_CATEGORY_LABELS[photo.category]}</p><p className="text-xs text-slate-500">{photo.originalFilename}</p></div><button ref={close} onClick={onClose} aria-label="Close photo viewer" className="rounded-lg p-2 focus-visible:ring-2 focus-visible:ring-indigo-500"><X className="size-5" /></button></header><div className="relative flex min-h-0 flex-1 items-center justify-center bg-slate-950"><img src={photo.viewUrl} alt={`${ASSIGNMENT_PHOTO_CATEGORY_LABELS[photo.category]} evidence: ${photo.originalFilename}`} className="max-h-[70vh] max-w-full object-contain" />{count > 1 ? <><button onClick={() => onMove(-1)} aria-label="Previous photo" className="absolute left-2 rounded-full bg-white/90 p-2 focus-visible:ring-2 focus-visible:ring-indigo-400"><ChevronLeft /></button><button onClick={() => onMove(1)} aria-label="Next photo" className="absolute right-2 rounded-full bg-white/90 p-2 focus-visible:ring-2 focus-visible:ring-indigo-400"><ChevronRight /></button></> : null}</div><footer className="flex flex-wrap items-center justify-between gap-3 p-3 text-xs text-slate-600"><div><p>Uploaded by <strong>{photo.uploadedByName}</strong></p><p>{photo.uploadedAt}{photo.caption ? ` · ${photo.caption}` : ""}</p></div><div className="flex gap-2"><a href={photo.viewUrl} download className="inline-flex min-h-9 items-center gap-1 rounded-lg border px-3 font-semibold"><Download className="size-4" />Download</a>{onDelete ? <button onClick={onDelete} className="inline-flex min-h-9 items-center gap-1 rounded-lg border border-rose-200 px-3 font-semibold text-rose-700"><Trash2 className="size-4" />Delete</button> : null}</div></footer></div></div>;
}