"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useState, useTransition } from "react";
import { Activity, CalendarDays, CheckCircle2, Clock3, Filter, ListChecks, RefreshCw, RotateCcw, TriangleAlert, Users } from "lucide-react";
import { dashboardPresetDates, type AssignmentDashboardFilters } from "@/features/assignment/assignment-dashboard-contract";
import type { AssignmentDashboardData, DashboardPerson } from "@/features/assignment/assignment-dashboard-metrics";
import type { AssignmentDashboardActivity } from "@/server/assignment/assignment-dashboard-repository";

const Charts = dynamic(() => import("./assignment-dashboard-charts"), { loading: () => <div role="status" className="h-80 animate-pulse rounded-2xl bg-slate-200 motion-reduce:animate-none"><span className="sr-only">Loading charts</span></div> });
interface RecentItem { key: string; assignmentId: string; state: string; at: string; person: string; }
type DashboardViewData = Omit<AssignmentDashboardData, "recentAssignments" | "recentCompletions" | "recentRevisits"> & { recentActivity: AssignmentDashboardActivity[]; exceededLimit: boolean; recentAssignments: RecentItem[]; recentCompletions: RecentItem[]; recentRevisits: RecentItem[] };
const duration = (value: number | null | undefined) => value === null || value === undefined ? "Unavailable" : value < 3600000 ? `${Math.round(value / 60000)} min` : `${Math.round(value / 360000) / 10} hr`;
const number = (value:number|null|undefined) => String(value ?? 0).replace(/\B(?=(\d{3})+(?!\d))/g, ",");

export function AssignmentDashboard({ filters, data, options }: { filters: AssignmentDashboardFilters; data: DashboardViewData; options: { coordinators: string[]; riggers: string[]; categories: string[] } }) {
  const router = useRouter(), pathname = usePathname(), params = useSearchParams();
  const [pending, startTransition] = useTransition();
  const [draft, setDraft] = useState(filters);
  const navigate = () => {
    const next = new URLSearchParams(params.toString());
    for (const key of ["preset", "startDate", "endDate", "coordinator", "rigger", "category", "status", "keyword"]) {
      const value = String(draft[key as keyof AssignmentDashboardFilters] ?? "");
      if (value) next.set(key, value); else next.delete(key);
    }
    startTransition(() => router.push(`${pathname}?${next}`));
  };
  const kpis = [
    ["Total Assignments", data.kpis.total, ListChecks], ["Open", data.kpis.open, Activity],
    ["Accepted", data.kpis.accepted, Activity], ["On Progress", data.kpis.onProgress, Activity],
    ["Paused", data.kpis.paused, Clock3], ["Completed Today", data.kpis.completedToday, ListChecks],
    ["Completed This Week", data.kpis.completedThisWeek, ListChecks], ["Completed This Month", data.kpis.completedThisMonth, ListChecks],
    ["Revisited", data.kpis.revisited, RotateCcw], ["Average Completion Time", duration(data.kpis.averageCompletionMs), Clock3],
    ["Average Response Time", duration(data.kpis.averageResponseMs), Clock3], ["Average Assignment Age", duration(data.kpis.averageAgeMs), Clock3],
  ] as const;
  const active = (data.kpis.open ?? 0) + (data.kpis.accepted ?? 0) + (data.kpis.onProgress ?? 0) + (data.kpis.paused ?? 0);
  const slaAttention = data.slaSummary.filter((item) => ["Warning", "Overdue", "Escalated"].includes(item.label)).reduce((sum, item) => sum + item.value, 0);
  return <div className="space-y-5" aria-busy={pending}>
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-700">Operations control</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Dashboard</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Workload, progress, SLA signals, and completion trends from existing Assignment data.</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs font-medium text-slate-600"><span className="inline-flex items-center gap-1.5"><CalendarDays aria-hidden="true" className="size-4 text-slate-400" />{filters.startDate} – {filters.endDate}</span><span className="inline-flex items-center gap-1.5"><ListChecks aria-hidden="true" className="size-4 text-slate-400" />{number(data.filteredCount)} filtered assignments</span></div></div><div className="flex gap-2"><Link href="/home/assignment" className="inline-flex min-h-11 items-center rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500">Assignment list</Link><button type="button" disabled={pending} onClick={() => startTransition(() => router.refresh())} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-indigo-700 px-4 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-indigo-500 disabled:opacity-60"><RefreshCw aria-hidden="true" className={`size-4 ${pending ? "animate-spin" : ""}`} />Refresh</button></div></header>
    {filters.error ? <p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{filters.error} The default range was applied.</p> : null}
    {data.exceededLimit ? <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">The range exceeds 5,000 records. Narrow the filters for exact analytics.</p> : null}
    <section aria-labelledby="dashboard-filters" className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 id="dashboard-filters" className="flex items-center gap-2 text-sm font-semibold"><Filter aria-hidden="true" className="size-4 text-indigo-700" />Filter dashboard</h2><div className="mt-3 flex flex-wrap gap-2" aria-label="Date range presets">{[["today","Today"],["week","This week"],["month","This month"],["last30","Last 30 days"]].map(([value,label]) => <button key={value} type="button" aria-pressed={draft.preset === value} onClick={() => setDraft((current) => ({ ...current, preset: value as AssignmentDashboardFilters["preset"], ...dashboardPresetDates(value as AssignmentDashboardFilters["preset"]) }))} className={`min-h-10 rounded-lg border px-3 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-indigo-500 ${draft.preset === value ? "border-indigo-700 bg-indigo-50 text-indigo-800" : "border-slate-300 text-slate-700"}`}>{label}</button>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Input label="Start date" type="date" value={draft.startDate} onChange={(value) => setDraft((current) => ({ ...current, startDate: value, preset: "custom" }))} />
      <Input label="End date" type="date" value={draft.endDate} onChange={(value) => setDraft((current) => ({ ...current, endDate: value, preset: "custom" }))} />
      <Select label="Coordinator" value={draft.coordinator} onChange={(value) => setDraft((current) => ({ ...current, coordinator: value }))} options={[["","All coordinators"], ...options.coordinators.map((value) => [value,value] as [string,string])]} />
      <Select label="Rigger" value={draft.rigger} onChange={(value) => setDraft((current) => ({ ...current, rigger: value }))} options={[["","All riggers"], ...options.riggers.map((value) => [value,value] as [string,string])]} />
      <Select label="Category" value={draft.category} onChange={(value) => setDraft((current) => ({ ...current, category: value }))} options={[["","All categories"], ...options.categories.map((value) => [value,value] as [string,string])]} />
      <Select label="Status" value={draft.status} onChange={(value) => setDraft((current) => ({ ...current, status: value }))} options={[["","All statuses"], ...["Open","Accepted","On Progress","Paused","Finished","Rejected","Dropped"].map((value) => [value,value] as [string,string])]} />
      <Input label="Keyword" value={draft.keyword} onChange={(value) => setDraft((current) => ({ ...current, keyword: value }))} placeholder="ID, tower, site, description, or person" />
    </div><div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={() => startTransition(() => router.push(pathname))} className="min-h-11 rounded-lg border border-slate-300 px-4 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-indigo-500">Reset</button><button type="button" onClick={navigate} disabled={pending} className="min-h-11 rounded-lg bg-indigo-700 px-5 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-indigo-500 disabled:opacity-60">{pending ? "Applying…" : "Apply filters"}</button></div></section>
    <section aria-labelledby="operational-summary" className="space-y-3"><div><h2 id="operational-summary" className="text-base font-semibold text-slate-950">Operational summary</h2><p className="mt-1 text-xs text-slate-500">Current signals for the selected cohort.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><PrimaryKpi label="Total assignments" value={data.kpis.total} helper="Selected created-date cohort" icon={ListChecks} tone="indigo"/><PrimaryKpi label="Active workload" value={active} helper="Open, accepted, in progress, or paused" icon={Activity} tone="cyan"/><PrimaryKpi label="Completed this month" value={data.kpis.completedThisMonth} helper={`${data.kpis.completedToday} completed today`} icon={CheckCircle2} tone="emerald"/><PrimaryKpi label="SLA attention" value={slaAttention} helper="Warning, overdue, or escalated" icon={TriangleAlert} tone={slaAttention ? "amber" : "emerald"}/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{kpis.slice(1).map(([label,value,Icon]) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-slate-500"><Icon aria-hidden="true" className="size-4 text-indigo-700" /><h3 className="text-xs font-semibold uppercase tracking-wide">{label}</h3></div><p className="mt-2 text-xl font-semibold tabular-nums text-slate-950">{value}</p></article>)}</div><p className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-xs text-slate-600"><strong>Average Pause Duration is unavailable.</strong> Resume timestamps are not stored, so no pause interval is inferred.</p></section>
    <section aria-label="SLA summary" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.slaSummary.filter((item) => ["On Track","Warning","Overdue","Escalated"].includes(item.label)).map((item) => <article key={item.label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="text-xs font-semibold uppercase tracking-wide text-slate-500">SLA {item.label}</h2><p className="mt-2 text-2xl font-semibold">{item.value}</p></article>)}</section>
    <Charts data={data} />
    <Workload title="Coordinator Analytics · current attribution" people={data.coordinators} coordinator />
    <Workload title="Rigger Analytics · current attribution" people={data.riggers} />
    <section className="grid gap-4 xl:grid-cols-2"><Recent title="Latest Assignments" items={data.recentAssignments} /><Recent title="Latest Completions" items={data.recentCompletions} /><Recent title="Latest Revisited" items={data.recentRevisits} /><ActivityFeed items={data.recentActivity} /></section>
  </div>;
}

function Input({ label, value, onChange, type = "text", placeholder }: { label:string; value:string; onChange:(value:string)=>void; type?:string; placeholder?:string }) { return <label className="text-sm font-medium">{label}<input type={type} value={value} maxLength={200} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-10 w-full rounded-lg border border-slate-300 px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500" /></label>; }
function Select({ label, value, onChange, options }: { label:string; value:string; onChange:(value:string)=>void; options:[string,string][] }) { return <label className="text-sm font-medium">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-10 w-full rounded-lg border border-slate-300 px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">{options.map(([key,text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Workload({ title, people, coordinator = false }: { title:string; people:DashboardPerson[]; coordinator?:boolean }) { const rows=people.slice(0,20), maximum=Math.max(1,...rows.map((person)=>person.total)); return <details open className="rounded-xl border border-slate-200 bg-white shadow-sm"><summary className="min-h-11 cursor-pointer px-4 py-3 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-indigo-500">{title}</summary><ol className="divide-y divide-slate-100 lg:hidden">{rows.map((person,index)=><li key={`${person.name}-${index}`} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{index+1}. {person.name}</p><p className="mt-1 text-xs text-slate-500">{person.active} active · {person.paused} paused · {person.completed} completed</p></div><strong className="tabular-nums">{person.total}</strong></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{width:`${person.total/maximum*100}%`}} /></div><p className="mt-2 text-xs text-slate-500">{coordinator?"Completed":"Accepted"}: {coordinator?person.completed:person.accepted} · Completion rate: {person.completionRate}% · Revisited: {person.revisited}</p></li>)}</ol><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[760px] text-left text-sm"><caption className="sr-only">{title} workload metrics</caption><thead className="bg-slate-50"><tr>{["Name","Total",coordinator?"Completed":"Accepted","Completed","Active","Paused","Avg completion","Revisited","Completion rate"].map((label, index) => <th key={`${label}-${index}`} scope="col" className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{rows.map((person, index) => <tr key={`${person.name}-${index}`} className="border-t border-slate-100 hover:bg-slate-50"><th scope="row" className="px-4 py-3">{person.name}</th><td className="px-4">{person.total}</td><td className="px-4">{coordinator?person.completed:person.accepted}</td><td className="px-4">{person.completed}</td><td className="px-4">{person.active}</td><td className="px-4">{person.paused}</td><td className="px-4">{duration(person.averageCompletionMs)}</td><td className="px-4">{person.revisited}</td><td className="px-4">{person.completionRate}%</td></tr>)}</tbody></table></div></details>; }
function Recent({ title, items }: { title:string; items:RecentItem[] }) { return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="text-sm font-semibold">{title}</h2>{items.length?<ul className="mt-3 divide-y">{items.map((item) => <li key={`${title}-${item.key}`} className="py-2"><Link href={`/home/assignment/${encodeURIComponent(item.key)}`} className="font-semibold text-indigo-700 focus-visible:ring-2">{item.assignmentId}</Link><p className="text-xs text-slate-500">{item.state} · {item.person || "Unassigned"} · {item.at}</p></li>)}</ul>:<p className="mt-3 text-sm text-slate-500">No activity in this range.</p>}</section>; }
function ActivityFeed({ items }: { items:AssignmentDashboardActivity[] }) { return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-semibold"><Users className="size-4 text-indigo-700" />Latest Comments & Photo Uploads</h2><p className="mt-1 text-xs text-slate-500">Bounded sample from the latest filtered Assignments.</p>{items.length?<ul className="mt-3 divide-y">{items.map((item,index) => <li key={`${item.type}-${item.assignmentKey}-${index}`} className="py-2 text-sm"><Link href={`/home/assignment/${encodeURIComponent(item.assignmentKey)}`} className="font-semibold text-indigo-700">{item.assignmentId}</Link><p className="truncate text-slate-700">{item.type === "comment" ? "Comment" : "Photo"} · {item.summary}</p><p className="text-xs text-slate-500">{item.actor} · {String(item.at)}</p></li>)}</ul>:<p className="mt-3 text-sm text-slate-500">No sampled comments or photos.</p>}</section>; }

function PrimaryKpi({ label, value, helper, icon: Icon, tone }: { label:string; value:number|null; helper:string; icon:typeof ListChecks; tone:"indigo"|"cyan"|"emerald"|"amber" }) { const tones={indigo:"bg-indigo-50 text-indigo-700",cyan:"bg-cyan-50 text-cyan-700",emerald:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700"}; return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</h3><p className="mt-2 text-3xl font-semibold tabular-nums tracking-tight text-slate-950">{number(value)}</p></div><span className={`rounded-lg p-2 ${tones[tone]}`}><Icon aria-hidden="true" className="size-5" /></span></div><p className="mt-3 text-xs leading-5 text-slate-500">{helper}</p></article>; }
