import "server-only";
import type {DataSnapshot,Database} from "firebase-admin/database";
import {firebaseAdminDatabase} from "@/lib/firebase/admin";
import type {RawAssignmentRecord,RawAssignmentSnapshotEntry} from "@/features/assignment/assignment-types";
import type {RawTowerRecord} from "@/features/tower/tower-types";
import {analyzeTowerAssignmentImpact,TOWER_ASSIGNMENT_SYNC_LIMIT} from "@/features/tower/tower-assignment-impact-contract";
import {buildAssignmentTowerSyncAudit,type AssignmentTowerSyncAuditRecord} from "@/features/tower/assignment-tower-sync-audit-contract";
import type {TowerAssignmentImpactRepository,TowerAssignmentSyncCommitInput,TowerAssignmentSyncCommitResult} from "./tower-assignment-impact-repository";
const entries=(snapshot:DataSnapshot)=>{const rows:RawAssignmentSnapshotEntry[]=[];snapshot.forEach(child=>{rows.push({key:child.key??"",value:child.val() as RawAssignmentRecord})});return rows};
export class FirebaseTowerAssignmentImpactRepository implements TowerAssignmentImpactRepository{
 constructor(private readonly database:Database=firebaseAdminDatabase){}
 async readRelated(towerId:string){const rows=entries(await this.database.ref("assignment").orderByChild("tower_id").equalTo(towerId).limitToFirst(TOWER_ASSIGNMENT_SYNC_LIMIT+1).once("value"));return{rows:rows.slice(0,TOWER_ASSIGNMENT_SYNC_LIMIT),overflow:rows.length>TOWER_ASSIGNMENT_SYNC_LIMIT}}
 reserveAssignmentAuditKey(assignmentKey:string){const key=this.database.ref(`assignment_audit/${assignmentKey}`).push().key;if(!key)throw new Error("Assignment audit key generation failed.");return key}
 async commitEligible(input:TowerAssignmentSyncCommitInput):Promise<TowerAssignmentSyncCommitResult>{let outcome:TowerAssignmentSyncCommitResult["outcome"]="not_found",committedImpact=null as import("@/features/tower/tower-assignment-impact-contract").TowerAssignmentImpact|null;const result=await this.database.ref().transaction(current=>{if(current===null)return current;const root=current as Record<string,unknown>,towers=(root.tower&&typeof root.tower==="object"?root.tower:{}) as Record<string,RawTowerRecord>,tower=towers[input.towerKey];if(!tower){outcome="not_found";return}if(Object.entries(input.expected).some(([field,value])=>(tower[field]??null)!==value)){outcome="conflict";return}const assignments=(root.assignment&&typeof root.assignment==="object"?root.assignment:{}) as Record<string,RawAssignmentRecord>,towerId=String(tower.tower_id??""),related=Object.entries(assignments).filter(([,record])=>String(record.tower_id??"")===towerId).map(([key,value])=>({key,value}));if(related.length>TOWER_ASSIGNMENT_SYNC_LIMIT){outcome="overflow";return}const nextTower={...tower};for(const[field,value]of Object.entries(input.updates)){if(value===null)delete nextTower[field];else nextTower[field]=value}const impact=analyzeTowerAssignmentImpact({towerKey:input.towerKey,currentTower:tower,nextTower,assignments:related});if(impact.impactToken!==input.impactToken){outcome="impact_conflict";return}if(impact.blockedCount){outcome="blocked";return}const nextAssignments={...assignments},assignmentAuditRoot=(root.assignment_audit&&typeof root.assignment_audit==="object"?root.assignment_audit:{}) as Record<string,Record<string,AssignmentTowerSyncAuditRecord>>,nextAssignmentAudits={...assignmentAuditRoot};for(const row of impact.assignments){if(row.eligibility!=="eligible"||!row.changedFields.length)continue;const currentAssignment=assignments[row.assignmentKey],nextAssignment={...currentAssignment};for(const[field,value]of Object.entries(row.updates)){if(value===null)delete nextAssignment[field];else nextAssignment[field]=value}nextAssignments[row.assignmentKey]=nextAssignment;const auditId=input.assignmentAuditIds[row.assignmentKey];if(!auditId){outcome="impact_conflict";return}const before=Object.fromEntries(row.changedFields.map(field=>[field,currentAssignment[field]??null])),after=Object.fromEntries(row.changedFields.map(field=>[field,nextAssignment[field]??null])),audit=buildAssignmentTowerSyncAudit({auditId,assignmentKey:row.assignmentKey,assignmentId:String(currentAssignment.assignment_id??""),towerKey:input.towerKey,towerId,towerAuditId:input.towerAudit.audit_id,actor:input.actor,occurredAt:input.occurredAt,before:before as Record<string,import("@/features/tower/tower-types").TowerScalar>,after:after as Record<string,import("@/features/tower/tower-types").TowerScalar>});nextAssignmentAudits[row.assignmentKey]={...(assignmentAuditRoot[row.assignmentKey]??{}),[auditId]:audit}}
 const towerAuditRoot=(root.tower_audit&&typeof root.tower_audit==="object"?root.tower_audit:{}) as Record<string,Record<string,unknown>>,summary={mode:"eligible",related_count:impact.relatedCount,eligible_count:impact.eligibleCount,updated_count:impact.updatedCount,preserved_count:impact.historicalCount,blocked_count:impact.blockedCount,overflow:impact.overflow};outcome="updated";committedImpact=impact;return{...root,tower:{...towers,[input.towerKey]:nextTower},assignment:nextAssignments,tower_audit:{...towerAuditRoot,[input.towerKey]:{...(towerAuditRoot[input.towerKey]??{}),[input.towerAudit.audit_id]:{...input.towerAudit,assignment_sync:summary}}},assignment_audit:nextAssignmentAudits}},undefined,false);return result.committed&&(outcome as TowerAssignmentSyncCommitResult["outcome"])==="updated"&&committedImpact?{outcome:"updated",impact:committedImpact}:{outcome:outcome as Exclude<TowerAssignmentSyncCommitResult["outcome"],"updated">}}
}