import "server-only";
import type {Database} from "firebase-admin/database";
import {firebaseAdminDatabase} from "@/lib/firebase/admin";
import {logTowerRuntime} from "@/lib/firebase/runtime-debug";
import type {RawTowerRecord,TowerScalar} from "@/features/tower/tower-types";
import {TOWER_RTDB_PATH} from "./tower-repository";
import type {TowerCommandRepository} from "./tower-command-repository";
import type{TowerAuditRecord}from"@/features/tower/tower-audit-contract";
const TOWER_AUDIT_PATH="tower_audit";
export class FirebaseTowerCommandRepository implements TowerCommandRepository{
 constructor(private readonly database:Database=firebaseAdminDatabase){}
 reserveKey(){const key=this.database.ref(TOWER_RTDB_PATH).push().key;if(!key)throw new Error("Tower key generation failed.");return key}
 reserveAuditKey(towerKey:string){const key=this.database.ref(`${TOWER_AUDIT_PATH}/${towerKey}`).push().key;if(!key)throw new Error("Tower audit key generation failed.");return key}
 async findByKey(key:string){const path=`${TOWER_RTDB_PATH}/${key}`,snapshot=await this.database.ref(`${TOWER_RTDB_PATH}/${key}`).once("value");logTowerRuntime("command-find",key,{path,exists:snapshot.exists()});return snapshot.exists()?snapshot.val() as RawTowerRecord:null}
 async updateFieldsWithAudit(key:string,updates:Record<string,TowerScalar>,expected:Record<string,TowerScalar>,audit:TowerAuditRecord){let outcome:"updated"|"not_found"|"conflict"="not_found",transactionExists=false;const result=await this.database.ref().transaction(current=>{if(current===null)return current;const root=current&&typeof current==="object"?current as Record<string,unknown>:{},towers=root[TOWER_RTDB_PATH]&&typeof root[TOWER_RTDB_PATH]==="object"?root[TOWER_RTDB_PATH] as Record<string,RawTowerRecord>:{};transactionExists=Boolean(towers[key]);if(!towers[key])return;if(Object.entries(expected).some(([field,value])=>(towers[key][field]??null)!==value)){outcome="conflict";return}outcome="updated";const next={...towers[key]};for(const[field,value]of Object.entries(updates)){if(value===null)delete next[field];else next[field]=value}const auditRoot=root[TOWER_AUDIT_PATH]&&typeof root[TOWER_AUDIT_PATH]==="object"?root[TOWER_AUDIT_PATH] as Record<string,unknown>:{},towerAudits=auditRoot[key]&&typeof auditRoot[key]==="object"?auditRoot[key] as Record<string,TowerAuditRecord>:{};return{...root,[TOWER_RTDB_PATH]:{...towers,[key]:next},[TOWER_AUDIT_PATH]:{...auditRoot,[key]:{...towerAudits,[audit.audit_id]:audit}}}},undefined,false);logTowerRuntime("command-transaction",key,{path:`${TOWER_RTDB_PATH}/${key}`,exists:transactionExists,branch:result.committed?"updated":outcome});return result.committed&&(outcome as "updated"|"not_found"|"conflict")==="updated"?"updated":outcome}
 async listExistingTowerIds(limit:number){const snapshot=await this.database.ref(TOWER_RTDB_PATH).orderByKey().limitToFirst(limit+1).once("value"),ids=new Set<string>();let count=0;snapshot.forEach(child=>{count++;const id=String((child.val() as RawTowerRecord)?.tower_id??"").trim().toUpperCase();if(id)ids.add(id)});return{ids,overflow:count>limit}}
 async createManyIfTowerIdsAvailable(records:Record<string,RawTowerRecord>,audits:Record<string,TowerAuditRecord>,maxExisting:number):Promise<{outcome:"created"|"conflict"|"capacity";conflicts:string[]}>{const wanted=new Set(Object.values(records).map(record=>String(record.tower_id).trim().toUpperCase()));let outcome:"conflict"|"capacity"="conflict",conflicts:string[]=[];const result=await this.database.ref().transaction(current=>{const databaseRoot=current&&typeof current==="object"?current as Record<string,unknown>:{},root=databaseRoot[TOWER_RTDB_PATH]&&typeof databaseRoot[TOWER_RTDB_PATH]==="object"?databaseRoot[TOWER_RTDB_PATH] as Record<string,RawTowerRecord>:{};if(Object.keys(root).length>maxExisting){outcome="capacity";return}const existing=new Set(Object.values(root).map(record=>String(record?.tower_id??"").trim().toUpperCase()));conflicts=[...wanted].filter(id=>existing.has(id));if(conflicts.length){outcome="conflict";return}const auditRoot=databaseRoot[TOWER_AUDIT_PATH]&&typeof databaseRoot[TOWER_AUDIT_PATH]==="object"?databaseRoot[TOWER_AUDIT_PATH] as Record<string,unknown>:{};return{...databaseRoot,[TOWER_RTDB_PATH]:{...root,...records},[TOWER_AUDIT_PATH]:{...auditRoot,...Object.fromEntries(Object.entries(audits).map(([towerKey,audit])=>[towerKey,{...((auditRoot[towerKey] as object)??{}),[audit.audit_id]:audit}]))}}},undefined,false);return{outcome:result.committed?"created":outcome,conflicts}}
 async createIfTowerIdAvailable(key:string,record:RawTowerRecord,audit:TowerAuditRecord):Promise<{outcome:"created"|"duplicate";key:string}>{let created=false,resolvedKey=key;const wanted=String(record.tower_id).trim().toUpperCase();const result=await this.database.ref().transaction(current=>{const databaseRoot=current&&typeof current==="object"?current as Record<string,unknown>:{},records=databaseRoot[TOWER_RTDB_PATH]&&typeof databaseRoot[TOWER_RTDB_PATH]==="object"?databaseRoot[TOWER_RTDB_PATH] as Record<string,RawTowerRecord>:{};const duplicate=Object.entries(records).find(([,value])=>String(value?.tower_id??"").trim().toUpperCase()===wanted);if(duplicate){resolvedKey=duplicate[0];return}created=true;const auditRoot=databaseRoot[TOWER_AUDIT_PATH]&&typeof databaseRoot[TOWER_AUDIT_PATH]==="object"?databaseRoot[TOWER_AUDIT_PATH] as Record<string,unknown>:{};return{...databaseRoot,[TOWER_RTDB_PATH]:{...records,[key]:record},[TOWER_AUDIT_PATH]:{...auditRoot,[key]:{[audit.audit_id]:audit}}}},undefined,false);return{outcome:result.committed&&created?"created":"duplicate",key:resolvedKey}}
}
