import { normalizeTowerImportRow, type TowerImportRow, type TowerImportRowResult, type TowerImportValidation } from "@/features/tower/tower-import-contract";
import { buildTowerAuditEvent, type TowerAuditActor, type TowerAuditRecord } from "@/features/tower/tower-audit-contract";
import type { RawTowerRecord } from "@/features/tower/tower-types";
import type { TowerCommandRepository } from "./tower-command-repository";
export const TOWER_IMPORT_EXISTING_SCAN_LIMIT=1000;
export class TowerImportError extends Error{constructor(public readonly code:string,message:string,public readonly status=400){super(message)}}
const errorInfo=(message:string)=>{const lower=message.toLowerCase();if(lower.includes("tower id"))return{code:lower.includes("required")?"missing_required_value":"invalid_tower_id",field:"tower_id",message};if(lower.includes("latitude"))return{code:"invalid_latitude",field:"latitude",message};if(lower.includes("longitude"))return{code:"invalid_longitude",field:"longitude",message};const radio=["g900","g1800","u850","u900","u2100","l700","l850","l900","l1800","l2100","l2300","l2600"].find(v=>lower.includes(v));if(radio)return{code:"invalid_radio_value",field:radio,message};const required=["site name","region","cluster"].find(v=>lower.includes(v));return{code:required?"missing_required_value":"invalid_value",field:required==="site name"?"sitename":required==="cluster"?"new_cluster_name":required??"row",message}};
export class TowerImportService{
 constructor(private repository:TowerCommandRepository,private readonly now=()=>new Date()){}
 async validate(rows:TowerImportRow[]){return(await this.prepare(rows)).validation}
 async commit(rows:TowerImportRow[],actor:TowerAuditActor){const{validation,records}=await this.prepare(rows);if(!validation.canCommit)throw new TowerImportError("IMPORT_VALIDATION_FAILED","Import contains invalid or conflicting rows. No Towers were created.",422);const keyed=Object.fromEntries(records.map(record=>[this.repository.reserveKey(),record])),occurredAt=this.now().toISOString(),audits=Object.fromEntries(Object.entries(keyed).map(([key,record])=>{const auditId=this.repository.reserveAuditKey(key);return[key,buildTowerAuditEvent({auditId,entityKey:key,towerId:String(record.tower_id),action:"tower_imported",source:"bulk_import",actor,occurredAt,after:record})]})) as Record<string,TowerAuditRecord>;const result=await this.repository.createManyIfTowerIdsAvailable(keyed,audits,TOWER_IMPORT_EXISTING_SCAN_LIMIT);if(result.outcome==="capacity")throw new TowerImportError("IMPORT_CAPACITY","Tower collection exceeds the safe import scan limit. No Towers were created.",409);if(result.outcome==="conflict")throw new TowerImportError("STALE_CONFLICT","Tower data changed after validation. No Towers were created.",409);const keys=Object.keys(keyed);return{...validation,importedRows:records.length,firstKey:keys[0]??null,rows:validation.rows.map(row=>({...row,status:"imported" as const}))}}
 private async prepare(rows:TowerImportRow[]){const existing=await this.repository.listExistingTowerIds(TOWER_IMPORT_EXISTING_SCAN_LIMIT);if(existing.overflow)throw new TowerImportError("IMPORT_CAPACITY","Tower collection exceeds the safe import scan limit.",409);const counts=new Map<string,number>();for(const row of rows){const id=String(row.tower_id??"").trim().toUpperCase();if(id)counts.set(id,(counts.get(id)??0)+1)}const results:TowerImportRowResult[]=[],records:RawTowerRecord[]=[];for(const row of rows){const rawId=String(row.tower_id??"").trim().toUpperCase(),base={rowNumber:row.rowNumber,towerId:rawId,siteName:String(row.sitename??""),region:String(row.region??""),cluster:String(row.new_cluster_name??"")};if(rawId&&(counts.get(rawId)??0)>1){results.push({...base,status:"duplicate_in_file",errors:[{code:"duplicate_tower_id_in_file",field:"tower_id",message:"Duplicate normalized Tower ID in uploaded file."}]});continue}if(rawId&&existing.ids.has(rawId)){results.push({...base,status:"already_exists",errors:[{code:"tower_already_exists",field:"tower_id",message:"Tower ID already exists."}]});continue}try{const record=normalizeTowerImportRow(row);records.push(record);results.push({...base,towerId:String(record.tower_id),siteName:String(record.sitename),region:String(record.region),cluster:String(record.new_cluster_name),status:"valid",errors:[],normalized:record})}catch(error){results.push({...base,status:"invalid",errors:[errorInfo(error instanceof Error?error.message:"Invalid Tower row.")]})}}const validRows=results.filter(r=>r.status==="valid").length,invalidRows=results.filter(r=>r.status==="invalid").length,duplicateRows=results.filter(r=>r.status==="duplicate_in_file").length,conflictRows=results.filter(r=>r.status==="already_exists").length;return{validation:{totalRows:results.length,validRows,invalidRows,duplicateRows,conflictRows,canCommit:validRows===results.length,rows:results} satisfies TowerImportValidation,records}}
}
