import "server-only";
import {prepareTowerEdit,TOWER_EDIT_FIELDS} from "@/features/tower/tower-edit-contract";
import {analyzeTowerAssignmentImpact,type TowerAssignmentImpact,type TowerAssignmentImpactPreview} from "@/features/tower/tower-assignment-impact-contract";
import {buildTowerAuditEvent,type TowerAuditActor,type TowerAuditRecord} from "@/features/tower/tower-audit-contract";
import type {TowerScalar} from "@/features/tower/tower-types";
import type {TowerCommandRepository} from "./tower-command-repository";
import type {TowerAssignmentImpactRepository} from "./tower-assignment-impact-repository";
export type AssignmentSyncMode="none"|"eligible";
export class TowerAssignmentImpactError extends Error{constructor(public readonly code:"INVALID"|"NOT_FOUND"|"CONFLICT"|"IMPACT_CONFLICT"|"BLOCKED"|"OVERFLOW",message:string){super(message)}}
function payload(input:unknown){const value=input&&typeof input==="object"&&!Array.isArray(input)?input as Record<string,unknown>:null,values=value?.values,baseline=value?.baseline;if(!values||!baseline||typeof values!=="object"||Array.isArray(values)||typeof baseline!=="object"||Array.isArray(baseline))throw new TowerAssignmentImpactError("INVALID","Tower values and edit baseline are required.");const expected=baseline as Record<string,unknown>;if(Object.keys(expected).length!==TOWER_EDIT_FIELDS.length||Object.keys(expected).some(field=>!TOWER_EDIT_FIELDS.includes(field))||Object.values(expected).some(item=>item!==null&&!["string","number","boolean"].includes(typeof item)))throw new TowerAssignmentImpactError("INVALID","Tower edit baseline is invalid.");const sync=value?.assignmentSync&&typeof value.assignmentSync==="object"&&!Array.isArray(value.assignmentSync)?value.assignmentSync as Record<string,unknown>:null,mode=(sync?.mode??"none") as AssignmentSyncMode;if(!["none","eligible"].includes(mode))throw new TowerAssignmentImpactError("INVALID","Invalid Assignment synchronization mode.");return{values:values as Record<string,unknown>,expected:expected as Record<string,TowerScalar>,mode,impactToken:typeof value?.impactToken==="string"?value.impactToken:""}}
export class TowerAssignmentImpactService{
 constructor(private readonly towers:TowerCommandRepository,private readonly impacts:TowerAssignmentImpactRepository,private readonly now=()=>new Date()){}
 private async prepare(key:string,input:unknown){const parsed=payload(input),current=await this.towers.findByKey(key);if(!current)throw new TowerAssignmentImpactError("NOT_FOUND","Tower not found.");if(!String(current.tower_id??"").trim())throw new TowerAssignmentImpactError("INVALID","Stored Tower ID is missing.");let prepared;try{prepared=prepareTowerEdit(current,parsed.values)}catch(error){throw new TowerAssignmentImpactError("INVALID",error instanceof Error?error.message:"Invalid Tower payload.")}const related=await this.impacts.readRelated(String(current.tower_id)),impact=analyzeTowerAssignmentImpact({towerKey:key,currentTower:current,nextTower:prepared.record,assignments:related.rows,overflow:related.overflow});return{...parsed,current,prepared,impact}}
 async preview(key:string,input:unknown):Promise<TowerAssignmentImpactPreview>{const impact=(await this.prepare(key,input)).impact;return{...impact,assignments:impact.assignments.map(({updates,...row})=>{void updates;return row})}}
 async commit(key:string,input:unknown,actor:TowerAuditActor){const plan=await this.prepare(key,input),changed=Object.keys(plan.prepared.updates).length>0;if(!changed)return{key,tower_id:plan.current.tower_id,changed:false,record:plan.prepared.record,assignmentSync:{mode:plan.mode,...summary(plan.impact)}};if(plan.impact.overflow&&plan.mode==="eligible")throw new TowerAssignmentImpactError("OVERFLOW","Related Assignments exceed the synchronization safety limit.");if(plan.impact.blockedCount&&plan.mode==="eligible")throw new TowerAssignmentImpactError("BLOCKED","Assignment synchronization is blocked by unknown lifecycle records.");if(plan.mode==="eligible"&&plan.impactToken!==plan.impact.impactToken)throw new TowerAssignmentImpactError("IMPACT_CONFLICT","Assignment impact changed after review. Review the latest impact before saving.");const auditId=this.towers.reserveAuditKey(key),occurredAt=this.now().toISOString(),before=Object.fromEntries(Object.keys(plan.prepared.updates).map(field=>[field,plan.current[field]??null])),after=Object.fromEntries(Object.keys(plan.prepared.updates).map(field=>[field,plan.prepared.record[field]??null])),baseAudit=buildTowerAuditEvent({auditId,entityKey:key,towerId:String(plan.current.tower_id),action:"tower_updated",source:"manual_edit",actor,occurredAt,before,after});if(plan.mode==="none"){const audit={...baseAudit,assignment_sync:{mode:"none",related_count:plan.impact.relatedCount,eligible_count:plan.impact.eligibleCount,updated_count:0,preserved_count:plan.impact.historicalCount,blocked_count:plan.impact.blockedCount,overflow:plan.impact.overflow}} as TowerAuditRecord;const outcome=await this.towers.updateFieldsWithAudit(key,plan.prepared.updates,plan.expected,audit);handle(outcome);return{key,tower_id:plan.current.tower_id,changed:true,record:plan.prepared.record,assignmentSync:{mode:"none",...summary(plan.impact)}}}const assignmentAuditIds=Object.fromEntries(plan.impact.assignments.filter(row=>row.eligibility==="eligible"&&row.changedFields.length).map(row=>[row.assignmentKey,this.impacts.reserveAssignmentAuditKey(row.assignmentKey)])),result=await this.impacts.commitEligible({towerKey:key,updates:plan.prepared.updates,expected:plan.expected,towerAudit:baseAudit,actor,occurredAt,impactToken:plan.impactToken,assignmentAuditIds});if(result.outcome!=="updated")throw outcomeError(result.outcome);return{key,tower_id:plan.current.tower_id,changed:true,record:plan.prepared.record,assignmentSync:{mode:"eligible",...summary(result.impact)}}}
}
const summary=(impact:TowerAssignmentImpact)=>({relatedCount:impact.relatedCount,updatedCount:impact.updatedCount,unchangedCount:Math.max(0,impact.eligibleCount-impact.updatedCount),preservedCount:impact.historicalCount,blockedCount:impact.blockedCount,affectedSnapshotFields:impact.synchronizableFields});
function handle(outcome:"updated"|"not_found"|"conflict"){if(outcome==="not_found")throw new TowerAssignmentImpactError("NOT_FOUND","Tower not found.");if(outcome==="conflict")throw new TowerAssignmentImpactError("CONFLICT","This Tower changed after you opened it. Reload the latest values before editing again.")}
function outcomeError(outcome:string){if(outcome==="not_found")return new TowerAssignmentImpactError("NOT_FOUND","Tower not found.");if(outcome==="overflow")return new TowerAssignmentImpactError("OVERFLOW","Related Assignments exceed the synchronization safety limit.");if(outcome==="blocked")return new TowerAssignmentImpactError("BLOCKED","Assignment synchronization is blocked by unknown lifecycle records.");return new TowerAssignmentImpactError(outcome==="conflict"?"CONFLICT":"IMPACT_CONFLICT",outcome==="conflict"?"This Tower changed after you opened it. Reload the latest values before editing again.":"Assignment impact changed after review. Review the latest impact before saving.")}
