import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import test from "node:test";
import { createSigninHandler, createResetPasswordHandler, createUpdateUserDetailsHandler, createSignoutHandler } from "../../src/server/mobile-api/routes/auth-profile-handlers.mjs";
import { createMobileSigninService, createMobileResetPasswordService, createMobileProfileService } from "../../src/server/mobile-api/services/mobile-auth-profile-services.mjs";
import { mobileLoginUser, mobilePrivilegeRows, mobileProfileBody } from "../fixtures/mobile-auth-profile-fixtures.js";
const request=(url="https://example.invalid/read",body={})=>({nextUrl:new URL(url),headers:new Headers(),json:async()=>body});
function dependencies(options={}) { const operations=[]; return { operations, auth:{ async signIn(email,password){operations.push({type:"signIn",email,password:"[redacted]"}); if(options.authError)throw options.authError; return {token:"sanitized-token"};}, async sendPasswordReset(email){operations.push({type:"resetPassword",email}); if(options.authError)throw options.authError;} }, repo:{ async findUsersByEmail(email){operations.push({type:"read",path:"user",orderBy:"email",equalTo:email}); if(options.rtdbError)throw options.rtdbError; return options.users??[mobileLoginUser];}, async listPrivileges(){operations.push({type:"read",path:"privilege",orderBy:"category"}); return mobilePrivilegeRows;}, async writeLoginLog(log){operations.push({type:"write",path:"log",record:log});}, async updateUsersByEmail(email,body){operations.push({type:"update",path:"user",email,body}); if(options.rtdbError)throw options.rtdbError;} } }; }
test("signin preserves successful DTO, cookie, read order, timestamp, and login log",async()=>{const d=dependencies(); const service=createMobileSigninService({authentication:d.auth,repository:d.repo,clock:()=>({date:"2026-07-27",datetime:"2026-07-27 12:34:56"})}); const response=await createSigninHandler(service)(request(undefined,{email:"RIGGER@EXAMPLE.INVALID",password:"secret",browser:"android",ip_address:"sample"})); const body=await response.json(); assert.equal(response.status,200); assert.equal(body.data.email,mobileLoginUser.email); assert.equal(body.data.privilege[0].children.length,1); assert.match(response.headers.get("set-cookie"),/^__session=sanitized-token/); await new Promise(setImmediate); assert.deepEqual(d.operations.map(x=>x.type),["signIn","read","read","write"]); assert.equal(d.operations[3].record.datetime,"2026-07-27 12:34:56"); assert.equal(Object.hasOwn(d.operations[3].record,"token_id"),false); assert.equal(JSON.stringify(d.operations[3].record).includes("sanitized-token"),false); assert.equal(JSON.stringify(d.operations[3].record).includes("secret"),false);});
test("signin preserves missing credentials and known/unknown Auth failures",async()=>{let r=await createSigninHandler({signIn(){throw new Error("unused")}})(request(undefined,{})); assert.equal(r.status,400); assert.equal((await r.json()).data,"Email and password are required"); for(const [code,status,text] of [["auth/wrong-password",401,"incorrect"],["auth/user-disabled",401,"disabled"],["auth/user-not-found",401,"not registered"],["auth/other",500,"raw auth"]]){const e=new Error("raw auth");e.code=code;const d=dependencies({authError:e});r=await createSigninHandler(createMobileSigninService({authentication:d.auth,repository:d.repo,clock:()=>({})}))(request(undefined,{email:"x",password:"x"}));assert.equal(r.status,status);assert.match((await r.json()).data,new RegExp(text));}});
test("signin preserves missing profile and RTDB failure as raw 500",async()=>{for(const d of [dependencies({users:[]}),dependencies({rtdbError:new Error("user read failed")})]){const r=await createSigninHandler(createMobileSigninService({authentication:d.auth,repository:d.repo,clock:()=>({})}))(request(undefined,{email:"x",password:"x"}));assert.equal(r.status,500);assert.equal((await r.json()).message,"failed");}});
test("resetPassword preserves success and mapped/raw errors",async()=>{let d=dependencies();let h=createResetPasswordHandler(createMobileResetPasswordService(d.auth));let r=await h(request("https://example.invalid/read?email=rigger%40example.invalid"));assert.equal((await r.json()).data,"The link reset password has been sent to your email address");for(const [code,status] of [["auth/user-not-found",401],["auth/internal",500]]){const e=new Error("reset raw");e.code=code;d=dependencies({authError:e});r=await createResetPasswordHandler(createMobileResetPasswordService(d.auth))(request());assert.equal(r.status,status);}});
test("profile update passes arbitrary body, updates by email, and preserves raw errors",async()=>{let d=dependencies();let r=await createUpdateUserDetailsHandler(createMobileProfileService(d.repo))(request("https://example.invalid/read?email=rigger%40example.invalid",mobileProfileBody));assert.deepEqual((await r.json()).data,mobileProfileBody);assert.equal(d.operations[0].email,"rigger@example.invalid");d=dependencies({rtdbError:new Error("profile failed")});r=await createUpdateUserDetailsHandler(createMobileProfileService(d.repo))(request("https://example.invalid/read",mobileProfileBody));assert.equal(r.status,500);assert.equal((await r.json()).data,"profile failed");});
test("signout is idempotent without a token and revokes a verified user",async()=>{const operations=[];const handler=createSignoutHandler({async verify(token){operations.push(["verify",token]);return {uid:"uid-sample"};},async revoke(uid){operations.push(["revoke",uid]);}});let response=await handler(request());assert.equal(response.status,200);assert.match(response.headers.get("set-cookie"),/Max-Age=0/);const authenticated=request();authenticated.headers.set("authorization","Bearer sanitized-token");response=await handler(authenticated);assert.equal(response.status,200);assert.deepEqual(operations,[["verify","sanitized-token"],["revoke","uid-sample"]]);assert.deepEqual(await response.json(),{code:200,message:"LOGOUT.",data:{uid:"uid-sample"}});});
for(const route of ["signin","signout","resetPassword","updateUserDetails"]){test(`${route} exact path exposes legacy method fallthrough`,()=>{const source=fs.readFileSync(path.join(process.cwd(),"src/app/api/mobile",route,"route.ts"),"utf8");for(const method of ["GET","POST","PUT","PATCH","DELETE","OPTIONS","HEAD"])assert.match(source,new RegExp(`\\b${method}\\b`));});}
test("auth fixtures contain no real secret material",()=>{const source=fs.readFileSync(path.join(process.cwd(),"tests/fixtures/mobile-auth-profile-fixtures.js"),"utf8");assert.doesNotMatch(source,/PRIVATE KEY|eyJ[A-Za-z0-9_-]{20,}[.]eyJ|AIza[0-9A-Za-z_-]{20,}|Bearer\s+|gmail[.]com/i);assert.match(source,/example[.]invalid/);});

test("signout rejects malformed and invalid or revoked tokens without leaking verifier errors",async()=>{let handler=createSignoutHandler({async verify(){throw new Error("sensitive verifier detail");},async revoke(){throw new Error("unused");}});let malformed=request();malformed.headers.set("authorization","Basic unsupported");let response=await handler(malformed);assert.equal(response.status,401);assert.doesNotMatch(JSON.stringify(await response.json()),/unsupported|sensitive/i);let invalid=request();invalid.headers.set("authorization","Bearer invalid-fixture");response=await handler(invalid);assert.equal(response.status,401);assert.doesNotMatch(JSON.stringify(await response.json()),/verifier/i);});
test("signout sanitizes revocation failure",async()=>{const handler=createSignoutHandler({async verify(){return {uid:"uid-sample"};},async revoke(){throw new Error("sensitive revoke detail");}});const authenticated=request();authenticated.headers.set("authorization","Bearer sanitized-token");const response=await handler(authenticated);assert.equal(response.status,401);assert.doesNotMatch(JSON.stringify(await response.json()),/revoke|sensitive/i);});
test("signout does not require a mutable profile and repeated logout remains idempotent",async()=>{let revoked=false;const handler=createSignoutHandler({async verify(){return {uid:"uid-without-profile"};},async revoke(){revoked=true;}});const authenticated=request();authenticated.headers.set("authorization","Bearer sanitized-token");let response=await handler(authenticated);assert.equal(response.status,200);assert.equal(revoked,true);response=await handler(request());assert.equal(response.status,200);assert.match((await response.json()).data,/already logout/i);});
