const obj=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
const txt=(v,max=500)=>v==null?"":String(v).trim().slice(0,max);
const sensitive=/(password|passwd|secret|token|authorization|private.?key|service.?account|credential|api.?key|base64|bytes)/i;
export function redactAuditValue(value,key=""){if(sensitive.test(key))return "[REDACTED]";if(Array.isArray(value))return value.slice(0,50).map(v=>redactAuditValue(v,key));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).slice(0,100).map(([k,v])=>[k,redactAuditValue(v,k)]));if(typeof value==="string"&&/(?:[?&](?:token|alt)=)|Bearer\s/i.test(value))return "[REDACTED]";return value}
export function normalizeAuditTimestamp(raw){let ms=null;if(typeof raw==="number"&&Number.isFinite(raw))ms=raw<1e12?raw*1000:raw;else if(typeof raw==="string"&&raw.trim()){const numeric=Number(raw);if(Number.isFinite(numeric)&&/^\d+(?:\.\d+)?$/.test(raw.trim()))ms=numeric<1e12?numeric*1000:numeric;else{const parsed=Date.parse(raw);if(Number.isFinite(parsed))ms=parsed}}return{raw:raw??null,valid:Number.isFinite(ms),epochMs:Number.isFinite(ms)?ms:null,iso:Number.isFinite(ms)?new Date(ms).toISOString():null}}
const labels={assignment_created:"Assignment created",assignment_revisited:"Assignment revisited",assignment_tower_synchronized:"Assignment tower synchronized",assignment_full_tower_synchronized:"Assignment full tower synchronized",tower_created:"Tower created",tower_updated:"Tower updated",tower_imported:"Tower imported","user.deactivated":"User deactivated","user.reactivated":"User activated","user.invited":"User invited","user.role.updated":"User role updated","privilege.role.updated":"Privilege updated",profile_self_service_update:"Profile updated",profile_photo_uploaded:"Profile photo uploaded",profile_photo_replaced:"Profile photo replaced",profile_photo_removed:"Profile photo removed",administrator_identity_repair:"Firebase identity repaired"};
export const auditActionLabel=action=>labels[action]??txt(action||"Unknown action",100).replaceAll(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export function auditSeverity(action){const a=txt(action).toLowerCase();if(/identity.*repair|privilege.*deleted|maintenance.*commit/.test(a))return"critical";if(/deactiv|removed|failed|conflict|revok|reassign/.test(a))return"warning";return"info"}
const moduleFor=(root,resource,action)=>root==="assignment_audit"?"assignment":root==="tower_audit"?"tower":({user:"user",role:"role",privilege:"privilege",user_profile:"profile",user_profile_photo:"profile",assignment:"assignment",tower:"tower",cell:"cell",import:"import",maintenance:"maintenance",authentication:"authentication"}[txt(resource).toLowerCase()]??(/profile/.test(action)?"profile":/auth|session/.test(action)?"authentication":"unknown"));
export function normalizeAuditEvent(sourceRoot,parentKey,eventKey,raw){const value=obj(raw),admin=sourceRoot==="administrator_audit",timestamp=normalizeAuditTimestamp(admin?value.timestamp:value.occurred_at??value.timestamp),action=txt(value.action,120),resource=txt(value.resourceType??value.resource_type,100),moduleName=moduleFor(sourceRoot,resource,action),targetKey=txt(admin?value.resourceIdentifier:value.entity_key??value.assignment_key??parentKey,256),targetId=txt(value.assignment_id??value.tower_id??value.target_id,256),before=redactAuditValue(obj(value.before)),after=redactAuditValue(obj(value.after)),changed=Array.isArray(value.changed_fields)?value.changed_fields.filter(x=>typeof x==="string").slice(0,100):[...new Set([...Object.keys(before),...Object.keys(after)])].sort();return{canonicalKey:`${sourceRoot}:${parentKey||"-"}:${eventKey}`,eventKey:txt(value.auditId??value.audit_id??eventKey,128)||eventKey,parentKey:parentKey||"",sourceRoot,module:moduleName,action,actionLabel:auditActionLabel(action),category:txt(value.source??resource,100),severity:auditSeverity(action),targetKey,targetId,targetLabel:txt(value.summary??value.target_label??targetId,500),actorUid:txt(value.administratorIdentifier??value.actor_uid,128),actorEmail:txt(value.administratorEmail??value.actor_email,320),actorName:txt(value.actor_name,200),timestamp,timestampRaw:timestamp.raw,reason:txt(value.reason??value.summary,500),changedFields:changed,before,after,metadata:redactAuditValue(Object.fromEntries(Object.entries(value).filter(([k])=>!["before","after"].includes(k)))),result:txt(value.result??value.status??value.outcome,100),malformed:!raw||typeof raw!=="object"||!action||!timestamp.valid}}
export function compareAuditValues(before,after){const b=obj(before),a=obj(after),keys=[...new Set([...Object.keys(b),...Object.keys(a)])].sort();return keys.map(field=>({field,before:Object.hasOwn(b,field)?b[field]:undefined,after:Object.hasOwn(a,field)?a[field]:undefined,state:!Object.hasOwn(b,field)?"added":!Object.hasOwn(a,field)?"removed":JSON.stringify(b[field])===JSON.stringify(a[field])?"unchanged":"changed"}))}
const val=(q,k)=>Array.isArray(q?.[k])?q[k][0]:q?.[k],clean=(q,k,n=200)=>txt(val(q,k),n),day=(v,end=false)=>v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?Date.parse(`${v}T${end?"23:59:59.999":"00:00:00.000"}Z`):null;
export function filterAuditEvents(events,q={}){const f={q:clean(q,"q",100),module:clean(q,"module",50),action:clean(q,"action",120),actor:clean(q,"actor",320),severity:clean(q,"severity",20),result:clean(q,"result",100),target:clean(q,"target",256),field:clean(q,"field",100),dateFrom:clean(q,"dateFrom",10),dateTo:clean(q,"dateTo",10),highRisk:clean(q,"highRisk",5)==="true"},needle=String(f.q).toLowerCase(),from=day(f.dateFrom)??-Infinity,to=day(f.dateTo,true)??Infinity;const items=events.filter(e=>{if(f.module&&e.module!==f.module||f.action&&e.action!==f.action||f.actor&&![e.actorUid,e.actorEmail,e.actorName].includes(f.actor)||f.severity&&e.severity!==f.severity||f.result&&e.result!==f.result||f.target&&![e.targetKey,e.targetId].some(v=>String(v).toLowerCase().includes(f.target.toLowerCase()))||f.field&&!e.changedFields.includes(f.field)||f.highRisk&&e.severity==="info")return false;if((f.dateFrom||f.dateTo)&&(!e.timestamp.valid||e.timestamp.epochMs<from||e.timestamp.epochMs>to))return false;return !needle||[e.action,e.actionLabel,e.targetId,e.targetLabel,e.actorName,e.actorEmail,e.module,e.reason].some(v=>String(v).toLowerCase().includes(needle))}).sort((a,b)=>(b.timestamp.epochMs??-Infinity)-(a.timestamp.epochMs??-Infinity)||a.sourceRoot.localeCompare(b.sourceRoot)||a.eventKey.localeCompare(b.eventKey));return{items,filters:f}}
const csvCell=v=>{let s=typeof v==="string"?v:JSON.stringify(v??"");if(/^[=+\-@\t\r]/.test(s))s=`'${s}`;return`"${s.replaceAll('"','""')}"`};
export function exportAuditCsv(events){const headers=["event_key","source_root","module","action","raw_action","timestamp","target_key","target_id","target_label","actor_name","actor_email","reason","severity","result","changed_fields","before","after","operation_id","batch_id"],rows=events.map(e=>[e.eventKey,e.sourceRoot,e.module,e.actionLabel,e.action,e.timestamp.iso??String(e.timestampRaw??""),e.targetKey,e.targetId,e.targetLabel,e.actorName,e.actorEmail,e.reason,e.severity,e.result,e.changedFields,redactAuditValue(e.before),redactAuditValue(e.after),e.metadata?.operation_id??e.metadata?.requestIdentifier??"",e.metadata?.batch_id??""]);return"\uFEFF"+[headers,...rows].map(row=>row.map(csvCell).join(",")).join("\r\n")}
export function auditTargetHref(event){if(!event.targetKey)return null;if(event.module==="assignment")return`/home/assignment/${encodeURIComponent(event.targetKey)}`;if(event.module==="tower")return`/home/towers/${encodeURIComponent(event.targetKey)}`;if(event.module==="user"||event.module==="profile")return`/home/admin/users/${encodeURIComponent(event.targetKey)}`;if(event.module==="cell")return`/home/cells/${encodeURIComponent(event.targetKey)}`;return null}