import { legacyFailure } from "../compatibility/response.mjs";
import { createMobileSecurityAudit } from "./audit.mjs";
import { resolveMobileSecurityMode } from "./config.mjs";
import { MOBILE_ROUTE_POLICIES } from "./policy.mjs";
import { resolveMobileToken } from "./token-resolver.mjs";

const authenticationReasons = new Set(["missing_token", "malformed_token", "invalid_token", "expired_token", "revoked_token"]);
function denialResponse(decision) {if(decision.reason==="unsafe_identifier")return legacyFailure(400,"failed","Invalid request identifier");if(decision.reason==="object_not_found")return legacyFailure(404,"failed","Resource not found");if(authenticationReasons.has(decision.reason))return legacyFailure(401,"failed","Authentication required");if(decision.reason==="security_internal_error")return legacyFailure(500,"failed","Internal mobile API error");return legacyFailure(403,"failed","Request is not authorized");}
async function inputFrom(request){const url=request.nextUrl||new URL(request.url),query=Object.fromEntries(url.searchParams.entries());let body={};if(!["GET","HEAD"].includes(request.method||"")){try{body=await request.clone().json();}catch{body={};}}return {query,body};}

export function createSecureMobileHandler(handler,route,dependencies){const policy=MOBILE_ROUTE_POLICIES[route];if(!policy)throw new Error(`Missing mobile security policy: ${route}`);return async(request)=>{const mode=dependencies.mode??resolveMobileSecurityMode(),started=Date.now(),context=dependencies.operational?.context?.(request)??{};const finish=(response,decision={},unhandledException=false)=>{const event={route,method:request.method,status:response.status,latencyMs:Date.now()-started,uid:decision.uid,securityMode:mode,compatibilityMode:"legacy-compatible",requestId:context.requestId,correlationId:context.correlationId,unhandledException};try{dependencies.operational?.metric?.(event);dependencies.operational?.logger?.request(event);}catch{}return response;};const run=async()=>{if(dependencies.operational?.compatibilityApiEnabled===false)return finish(legacyFailure(503,"failed","Mobile compatibility API is unavailable"));if(policy.access==="public"){const response=await handler(request);return finish(mode==="enforce"&&response.status>=500?legacyFailure(500,"failed","Internal mobile API error"):response);}let decision;try{decision=await dependencies.service.evaluate(policy,resolveMobileToken(request),await inputFrom(request));}catch{decision={allowed:false,reason:"security_internal_error"};}if(mode==="observe"){(dependencies.audit??createMobileSecurityAudit()).record({route,method:request.method,mode,allowed:decision.allowed,reason:decision.reason,uid:decision.uid,objectType:policy.access,objectId:decision.objectId,requestId:request.headers.get("x-request-id")});}if(mode==="enforce"&&!decision.allowed)return finish(denialResponse(decision),decision);const response=await handler(request);return finish(mode==="enforce"&&response.status>=500?legacyFailure(500,"failed","Internal mobile API error"):response,decision);};try{return await run();}catch(error){finish(new Response(null,{status:500}),{},true);throw error;}};}